# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details
import os
from typing import Any

from ecoscope.platform.tasks.analysis import summarize_df as summarize_df
from ecoscope.platform.tasks.config import set_workflow_details as set_workflow_details
from ecoscope.platform.tasks.filter import set_time_range as set_time_range
from ecoscope.platform.tasks.groupby import set_groupers as set_groupers
from ecoscope.platform.tasks.io import get_events as get_events
from ecoscope.platform.tasks.io import persist_df as persist_df
from ecoscope.platform.tasks.io import persist_text as persist_text
from ecoscope.platform.tasks.io import set_er_connection as set_er_connection
from ecoscope.platform.tasks.results import (
    create_table_widget_single_view as create_table_widget_single_view,
)
from ecoscope.platform.tasks.results import draw_table as draw_table
from ecoscope.platform.tasks.results import gather_dashboard as gather_dashboard
from ecoscope.platform.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope.platform.tasks.skip import any_is_empty_df as any_is_empty_df
from ecoscope.platform.tasks.skip import never as never
from ecoscope.platform.tasks.transformation import (
    add_temporal_index as add_temporal_index,
)
from ecoscope.platform.tasks.transformation import (
    extract_column_as_type as extract_column_as_type,
)
from ecoscope.platform.tasks.transformation import filter_df as filter_df
from ecoscope.platform.tasks.transformation import map_columns as map_columns
from ecoscope.platform.tasks.transformation import (
    normalize_json_column as normalize_json_column,
)
from ecoscope_workflows_ext_custom.tasks.io import (
    process_events_details as process_events_details,
)
from ecoscope_workflows_ext_custom.tasks.transformation import (
    drop_column_prefix as drop_column_prefix,
)
from ecoscope_workflows_ext_custom.tasks.transformation import (
    pivot_dataframe as pivot_dataframe,
)
from ecoscope_workflows_ext_mnc.tasks.transformation import (
    convert_columns_to_int as convert_columns_to_int,
)
from ecoscope_workflows_ext_mnc.tasks.transformation import (
    remove_brackets_from_column as remove_brackets_from_column,
)
from wt_contracts import validate as _validate
from wt_task import task

from .. import metadata as _metadata


def main(params: dict[str, Any], validate_params_schema: bool = True):
    if validate_params_schema:
        _validate(params, _metadata.load_params_schema())

    workflow_details = (
        task(set_workflow_details)
        .validate()
        .set_task_instance_id("workflow_details")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("workflow_details") or {}))
        .call()
    )

    time_range = (
        task(set_time_range)
        .validate()
        .set_task_instance_id("time_range")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("time_range") or {}))
        .call()
    )

    groupers = (
        task(set_groupers)
        .validate()
        .set_task_instance_id("groupers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(groupers=[], **(params.get("groupers") or {}))
        .call()
    )

    er_client_name = (
        task(set_er_connection)
        .validate()
        .set_task_instance_id("er_client_name")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("er_client_name") or {}))
        .call()
    )

    get_events_data = (
        task(get_events)
        .validate()
        .set_task_instance_id("get_events_data")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            client=er_client_name,
            time_range=time_range,
            event_columns=[
                "id",
                "time",
                "event_type",
                "event_category",
                "reported_by",
                "serial_number",
                "geometry",
                "created_at",
                "event_details",
                "patrols",
            ],
            event_types=[
                "balloon_landing",
                "airstrip_operations",
                "airstrip_maintenance",
                "airline_complaint",
            ],
            raise_on_empty=True,
            include_details=True,
            include_updates=False,
            include_related_events=False,
            include_null_geometry=False,
            include_display_values=False,
            force_point_geometry=True,
            **(params.get("get_events_data") or {}),
        )
        .call()
    )

    extract_event_date = (
        task(extract_column_as_type)
        .validate()
        .set_task_instance_id("extract_event_date")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=get_events_data,
            column_name="time",
            output_type="date",
            output_column_name="date",
            **(params.get("extract_event_date") or {}),
        )
        .call()
    )

    events_temporal = (
        task(add_temporal_index)
        .validate()
        .set_task_instance_id("events_temporal")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=extract_event_date,
            time_col="date",
            groupers=groupers,
            cast_to_datetime=True,
            format="mixed",
            **(params.get("events_temporal") or {}),
        )
        .call()
    )

    filter_balloon_events = (
        task(filter_df)
        .validate()
        .set_task_instance_id("filter_balloon_events")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            column_name="event_type",
            op="equal",
            value="balloon_landing",
            df=events_temporal,
            reset_index=False,
            **(params.get("filter_balloon_events") or {}),
        )
        .call()
    )

    filter_airstrip_operations = (
        task(filter_df)
        .validate()
        .set_task_instance_id("filter_airstrip_operations")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            column_name="event_type",
            op="equal",
            value="airstrip_operations",
            df=events_temporal,
            reset_index=False,
            **(params.get("filter_airstrip_operations") or {}),
        )
        .call()
    )

    filter_airstrip_maintenance = (
        task(filter_df)
        .validate()
        .set_task_instance_id("filter_airstrip_maintenance")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            column_name="event_type",
            op="equal",
            value="airstrip_maintenance",
            df=events_temporal,
            reset_index=False,
            **(params.get("filter_airstrip_maintenance") or {}),
        )
        .call()
    )

    filter_airline_complaints = (
        task(filter_df)
        .validate()
        .set_task_instance_id("filter_airline_complaints")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            column_name="event_type",
            op="equal",
            value="airline_complaint",
            df=events_temporal,
            reset_index=False,
            **(params.get("filter_airline_complaints") or {}),
        )
        .call()
    )

    process_balloon_details = (
        task(process_events_details)
        .validate()
        .set_task_instance_id("process_balloon_details")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=filter_balloon_events,
            client=er_client_name,
            map_to_titles=True,
            ordered=True,
            **(params.get("process_balloon_details") or {}),
        )
        .call()
    )

    normalize_balloon_values = (
        task(normalize_json_column)
        .validate()
        .set_task_instance_id("normalize_balloon_values")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            column="event_details",
            df=process_balloon_details,
            skip_if_not_exists=True,
            sort_columns=True,
            **(params.get("normalize_balloon_values") or {}),
        )
        .call()
    )

    drop_balloon_prefix = (
        task(drop_column_prefix)
        .validate()
        .set_task_instance_id("drop_balloon_prefix")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=normalize_balloon_values,
            prefix="event_details__",
            duplicate_strategy="keep_original",
            **(params.get("drop_balloon_prefix") or {}),
        )
        .call()
    )

    process_airstrip_details = (
        task(process_events_details)
        .validate()
        .set_task_instance_id("process_airstrip_details")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=filter_airstrip_operations,
            client=er_client_name,
            map_to_titles=True,
            ordered=True,
            **(params.get("process_airstrip_details") or {}),
        )
        .call()
    )

    normalize_airstrip_op_values = (
        task(normalize_json_column)
        .validate()
        .set_task_instance_id("normalize_airstrip_op_values")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            column="event_details",
            df=process_airstrip_details,
            skip_if_not_exists=True,
            sort_columns=True,
            **(params.get("normalize_airstrip_op_values") or {}),
        )
        .call()
    )

    drop_airstrip_op_prefix = (
        task(drop_column_prefix)
        .validate()
        .set_task_instance_id("drop_airstrip_op_prefix")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=normalize_airstrip_op_values,
            prefix="event_details__",
            duplicate_strategy="keep_original",
            **(params.get("drop_airstrip_op_prefix") or {}),
        )
        .call()
    )

    process_airstrip_maint_details = (
        task(process_events_details)
        .validate()
        .set_task_instance_id("process_airstrip_maint_details")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=filter_airstrip_maintenance,
            client=er_client_name,
            map_to_titles=True,
            ordered=True,
            **(params.get("process_airstrip_maint_details") or {}),
        )
        .call()
    )

    normalize_airstrip_maint_vals = (
        task(normalize_json_column)
        .validate()
        .set_task_instance_id("normalize_airstrip_maint_vals")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            column="event_details",
            df=process_airstrip_maint_details,
            skip_if_not_exists=True,
            sort_columns=True,
            **(params.get("normalize_airstrip_maint_vals") or {}),
        )
        .call()
    )

    drop_airstrip_maintenance_prefix = (
        task(drop_column_prefix)
        .validate()
        .set_task_instance_id("drop_airstrip_maintenance_prefix")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=normalize_airstrip_maint_vals,
            prefix="event_details__",
            duplicate_strategy="keep_original",
            **(params.get("drop_airstrip_maintenance_prefix") or {}),
        )
        .call()
    )

    process_airline_comp_details = (
        task(process_events_details)
        .validate()
        .set_task_instance_id("process_airline_comp_details")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=filter_airline_complaints,
            client=er_client_name,
            map_to_titles=True,
            ordered=True,
            **(params.get("process_airline_comp_details") or {}),
        )
        .call()
    )

    normalize_airline_comp_vals = (
        task(normalize_json_column)
        .validate()
        .set_task_instance_id("normalize_airline_comp_vals")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            column="event_details",
            df=process_airline_comp_details,
            skip_if_not_exists=True,
            sort_columns=True,
            **(params.get("normalize_airline_comp_vals") or {}),
        )
        .call()
    )

    drop_airline_complaint_prefix = (
        task(drop_column_prefix)
        .validate()
        .set_task_instance_id("drop_airline_complaint_prefix")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=normalize_airline_comp_vals,
            prefix="event_details__",
            duplicate_strategy="keep_original",
            **(params.get("drop_airline_complaint_prefix") or {}),
        )
        .call()
    )

    map_balloon_columns = (
        task(map_columns)
        .validate()
        .set_task_instance_id("map_balloon_columns")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=drop_balloon_prefix,
            drop_columns=[],
            retain_columns=[
                "date",
                "Balloon Company",
                "Where are clients staying?",
                "# of passengers",
            ],
            rename_columns={
                "Balloon Company": "balloon_company",
                "Where are clients staying?": "where_are_clients_staying",
                "# of passengers": "no_of_passengers",
            },
            raise_if_not_found=False,
            **(params.get("map_balloon_columns") or {}),
        )
        .call()
    )

    remove_balloon_brackets = (
        task(remove_brackets_from_column)
        .validate()
        .set_task_instance_id("remove_balloon_brackets")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=map_balloon_columns,
            columns=["balloon_company", "where_are_clients_staying"],
            **(params.get("remove_balloon_brackets") or {}),
        )
        .call()
    )

    rename_balloon_display = (
        task(map_columns)
        .validate()
        .set_task_instance_id("rename_balloon_display")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=remove_balloon_brackets,
            drop_columns=[],
            retain_columns=[],
            rename_columns={
                "date": "Date",
                "balloon_company": "Balloon Company",
                "where_are_clients_staying": "Where Are Clients Staying",
                "no_of_passengers": "No Of Passengers",
            },
            raise_if_not_found=False,
            **(params.get("rename_balloon_display") or {}),
        )
        .call()
    )

    persist_balloon_landing = (
        task(persist_df)
        .validate()
        .set_task_instance_id("persist_balloon_landing")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filetype="csv",
            df=rename_balloon_display,
            filename="balloon_landing_summary_table",
            **(params.get("persist_balloon_landing") or {}),
        )
        .call()
    )

    balloon_landing_table_html = (
        task(draw_table)
        .validate()
        .set_task_instance_id("balloon_landing_table_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            dataframe=rename_balloon_display,
            columns=None,
            table_config={
                "enable_sorting": True,
                "enable_filtering": True,
                "enable_download": False,
                "hide_header": False,
            },
            widget_id="Balloon Landing Summary",
            **(params.get("balloon_landing_table_html") or {}),
        )
        .call()
    )

    balloon_landing_table_html_url = (
        task(persist_text)
        .validate()
        .set_task_instance_id("balloon_landing_table_html_url")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="balloon_landing_summary_table.html",
            text=balloon_landing_table_html,
            **(params.get("balloon_landing_table_html_url") or {}),
        )
        .call()
    )

    balloon_landing_table_widget = (
        task(create_table_widget_single_view)
        .validate()
        .set_task_instance_id("balloon_landing_table_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Balloon Landing Summary",
            data=balloon_landing_table_html_url,
            **(params.get("balloon_landing_table_widget") or {}),
        )
        .call()
    )

    map_airstrip_op_columns = (
        task(map_columns)
        .validate()
        .set_task_instance_id("map_airstrip_op_columns")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=drop_airstrip_op_prefix,
            drop_columns=[],
            retain_columns=[],
            rename_columns={
                "Airline": "airline",
                "Arrival or departure": "arrival_departure",
                "Attendant": "attendant",
                "Camp/Lodge": "camp_lodge",
                "Number of clients": "no_of_clients",
            },
            raise_if_not_found=False,
            **(params.get("map_airstrip_op_columns") or {}),
        )
        .call()
    )

    remove_airstrip_op_brackets = (
        task(remove_brackets_from_column)
        .validate()
        .set_task_instance_id("remove_airstrip_op_brackets")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=map_airstrip_op_columns,
            columns=["airline", "arrival_departure", "attendant", "camp_lodge"],
            **(params.get("remove_airstrip_op_brackets") or {}),
        )
        .call()
    )

    convert_airstrip_op_ints = (
        task(convert_columns_to_int)
        .validate()
        .set_task_instance_id("convert_airstrip_op_ints")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=remove_airstrip_op_brackets,
            columns=["no_of_clients"],
            errors="coerce",
            fill_value=0,
            **(params.get("convert_airstrip_op_ints") or {}),
        )
        .call()
    )

    airstrip_op_summary_table = (
        task(summarize_df)
        .validate()
        .set_task_instance_id("airstrip_op_summary_table")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=convert_airstrip_op_ints,
            groupby_cols=["camp_lodge", "arrival_departure"],
            summary_params=[
                {
                    "display_name": "no_of_clients",
                    "aggregator": "sum",
                    "column": "no_of_clients",
                    "decimal_places": 0,
                }
            ],
            reset_index=True,
            **(params.get("airstrip_op_summary_table") or {}),
        )
        .call()
    )

    pivot_airstrip_ops = (
        task(pivot_dataframe)
        .validate()
        .set_task_instance_id("pivot_airstrip_ops")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=airstrip_op_summary_table,
            index="camp_lodge",
            columns=["arrival_departure"],
            values=["no_of_clients"],
            fill_value=0,
            **(params.get("pivot_airstrip_ops") or {}),
        )
        .call()
    )

    convert_pivot_int = (
        task(convert_columns_to_int)
        .validate()
        .set_task_instance_id("convert_pivot_int")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=pivot_airstrip_ops,
            columns=["arrival", "departure"],
            errors="coerce",
            fill_value=0,
            **(params.get("convert_pivot_int") or {}),
        )
        .call()
    )

    rename_airstrip_op_display = (
        task(map_columns)
        .validate()
        .set_task_instance_id("rename_airstrip_op_display")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=convert_pivot_int,
            drop_columns=[],
            retain_columns=[],
            rename_columns={
                "camp_lodge": "Camp Lodge",
                "no_of_clients_Arrival": "Arrival",
                "no_of_clients_Departure": "Departure",
            },
            raise_if_not_found=False,
            **(params.get("rename_airstrip_op_display") or {}),
        )
        .call()
    )

    persist_airstrip_operations = (
        task(persist_df)
        .validate()
        .set_task_instance_id("persist_airstrip_operations")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filetype="csv",
            df=rename_airstrip_op_display,
            filename="airstrip_operations_summary_table",
            **(params.get("persist_airstrip_operations") or {}),
        )
        .call()
    )

    airstrip_op_table_html = (
        task(draw_table)
        .validate()
        .set_task_instance_id("airstrip_op_table_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            dataframe=rename_airstrip_op_display,
            columns=None,
            table_config={
                "enable_sorting": True,
                "enable_filtering": True,
                "enable_download": False,
                "hide_header": False,
            },
            widget_id="Airstrip Operations Summary",
            **(params.get("airstrip_op_table_html") or {}),
        )
        .call()
    )

    airstrip_op_table_html_url = (
        task(persist_text)
        .validate()
        .set_task_instance_id("airstrip_op_table_html_url")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="airstrip_operations_summary_table.html",
            text=airstrip_op_table_html,
            **(params.get("airstrip_op_table_html_url") or {}),
        )
        .call()
    )

    airstrip_op_table_widget = (
        task(create_table_widget_single_view)
        .validate()
        .set_task_instance_id("airstrip_op_table_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Airstrip Operations Summary",
            data=airstrip_op_table_html_url,
            **(params.get("airstrip_op_table_widget") or {}),
        )
        .call()
    )

    map_airstrip_maintenance = (
        task(map_columns)
        .validate()
        .set_task_instance_id("map_airstrip_maintenance")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=drop_airstrip_maintenance_prefix,
            drop_columns=[],
            retain_columns=["date", "Maintenance type"],
            rename_columns={"Maintenance type": "maintenance_type"},
            raise_if_not_found=False,
            **(params.get("map_airstrip_maintenance") or {}),
        )
        .call()
    )

    rename_airstrip_maint_display = (
        task(map_columns)
        .validate()
        .set_task_instance_id("rename_airstrip_maint_display")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=map_airstrip_maintenance,
            drop_columns=[],
            retain_columns=[],
            rename_columns={"date": "Date", "maintenance_type": "Maintenance Type"},
            raise_if_not_found=False,
            **(params.get("rename_airstrip_maint_display") or {}),
        )
        .call()
    )

    persist_airstrip_maintenance = (
        task(persist_df)
        .validate()
        .set_task_instance_id("persist_airstrip_maintenance")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filetype="csv",
            df=rename_airstrip_maint_display,
            filename="airstrip_maintenance_summary_table",
            **(params.get("persist_airstrip_maintenance") or {}),
        )
        .call()
    )

    airstrip_maintenance_table_html = (
        task(draw_table)
        .validate()
        .set_task_instance_id("airstrip_maintenance_table_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            dataframe=rename_airstrip_maint_display,
            columns=None,
            table_config={
                "enable_sorting": True,
                "enable_filtering": True,
                "enable_download": False,
                "hide_header": False,
            },
            widget_id="Airstrip Maintenance Summary",
            **(params.get("airstrip_maintenance_table_html") or {}),
        )
        .call()
    )

    airstrip_maint_table_html_url = (
        task(persist_text)
        .validate()
        .set_task_instance_id("airstrip_maint_table_html_url")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="airstrip_maintenance_summary_table.html",
            text=airstrip_maintenance_table_html,
            **(params.get("airstrip_maint_table_html_url") or {}),
        )
        .call()
    )

    airstrip_maint_table_widget = (
        task(create_table_widget_single_view)
        .validate()
        .set_task_instance_id("airstrip_maint_table_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Airstrip Maintenance Summary",
            data=airstrip_maint_table_html_url,
            **(params.get("airstrip_maint_table_widget") or {}),
        )
        .call()
    )

    logistics_dashboard = (
        task(gather_dashboard)
        .validate()
        .set_task_instance_id("logistics_dashboard")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            details=workflow_details,
            widgets=[
                balloon_landing_table_widget,
                airstrip_op_table_widget,
                airstrip_maint_table_widget,
            ],
            time_range=time_range,
            groupers=groupers,
            **(params.get("logistics_dashboard") or {}),
        )
        .call()
    )

    return logistics_dashboard
