# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details


# ruff: noqa: E402

# %% [markdown]
# # Mnc Logistics Report
# TODO: top level description

# %% [markdown]
# ## Imports

import os

from ecoscope_workflows_core.tasks.config import (
    set_workflow_details as set_workflow_details,
)
from ecoscope_workflows_core.tasks.filter import set_time_range as set_time_range
from ecoscope_workflows_core.tasks.groupby import set_groupers as set_groupers
from ecoscope_workflows_core.tasks.io import set_er_connection as set_er_connection
from ecoscope_workflows_core.tasks.results import gather_dashboard as gather_dashboard
from ecoscope_workflows_core.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope_workflows_core.tasks.skip import any_is_empty_df as any_is_empty_df
from ecoscope_workflows_core.tasks.transformation import (
    add_temporal_index as add_temporal_index,
)
from ecoscope_workflows_core.tasks.transformation import (
    extract_column_as_type as extract_column_as_type,
)
from ecoscope_workflows_core.tasks.transformation import filter_df as filter_df
from ecoscope_workflows_core.tasks.transformation import map_columns as map_columns
from ecoscope_workflows_ext_custom.tasks.io import (
    process_events_details as process_events_details,
)
from ecoscope_workflows_ext_custom.tasks.transformation import (
    drop_column_prefix as drop_column_prefix,
)
from ecoscope_workflows_ext_ecoscope.tasks.analysis import summarize_df as summarize_df
from ecoscope_workflows_ext_ecoscope.tasks.io import get_events as get_events
from ecoscope_workflows_ext_ecoscope.tasks.io import persist_df as persist_df
from ecoscope_workflows_ext_ecoscope.tasks.transformation import (
    normalize_json_column as normalize_json_column,
)
from ecoscope_workflows_ext_mnc.tasks import capitalize_text as capitalize_text
from ecoscope_workflows_ext_mnc.tasks import convert_to_int as convert_to_int
from ecoscope_workflows_ext_mnc.tasks import pivot_df as pivot_df
from ecoscope_workflows_ext_mnc.tasks import (
    remove_brackets_from_column as remove_brackets_from_column,
)
from ecoscope_workflows_ext_mnc.tasks import (
    replace_missing_with_label as replace_missing_with_label,
)

# %% [markdown]
# ## Set workflow details

# %%
# parameters

workflow_details_params = dict(
    name=...,
    description=...,
    image_url=...,
)

# %%
# call the task


workflow_details = (
    set_workflow_details.set_task_instance_id("workflow_details")
    .handle_errors()
    .with_tracing()
    .partial(**workflow_details_params)
    .call()
)


# %% [markdown]
# ## Time range

# %%
# parameters

time_range_params = dict(
    since=...,
    until=...,
    timezone=...,
    time_format=...,
)

# %%
# call the task


time_range = (
    set_time_range.set_task_instance_id("time_range")
    .handle_errors()
    .with_tracing()
    .partial(**time_range_params)
    .call()
)


# %% [markdown]
# ## Set groupers

# %%
# parameters

groupers_params = dict()

# %%
# call the task


groupers = (
    set_groupers.set_task_instance_id("groupers")
    .handle_errors()
    .with_tracing()
    .partial(groupers=[], **groupers_params)
    .call()
)


# %% [markdown]
# ## Connect to ER

# %%
# parameters

er_client_name_params = dict(
    data_source=...,
)

# %%
# call the task


er_client_name = (
    set_er_connection.set_task_instance_id("er_client_name")
    .handle_errors()
    .with_tracing()
    .partial(**er_client_name_params)
    .call()
)


# %% [markdown]
# ## Retrieve all events

# %%
# parameters

get_events_data_params = dict()

# %%
# call the task


get_events_data = (
    get_events.set_task_instance_id("get_events_data")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        client=er_client_name,
        time_range=time_range,
        event_columns=[
            "id",
            "time",
            "event_type",
            "event_category",
            "reported_by",
            "serial_number",
            "geometry",
            "created_at",
            "event_details",
            "patrols",
        ],
        event_types=[
            "balloon_landing",
            "airstrip_operations",
            "airstrip_maintenance",
            "airline_complaint",
        ],
        raise_on_empty=True,
        include_details=True,
        include_updates=False,
        include_related_events=False,
        include_null_geometry=False,
        include_display_values=False,
        **get_events_data_params,
    )
    .call()
)


# %% [markdown]
# ## Extract date from events data

# %%
# parameters

extract_event_date_params = dict()

# %%
# call the task


extract_event_date = (
    extract_column_as_type.set_task_instance_id("extract_event_date")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=get_events_data,
        column_name="time",
        output_type="date",
        output_column_name="date",
        **extract_event_date_params,
    )
    .call()
)


# %% [markdown]
# ## Add temporal index on events

# %%
# parameters

events_temporal_params = dict()

# %%
# call the task


events_temporal = (
    add_temporal_index.set_task_instance_id("events_temporal")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=extract_event_date,
        time_col="date",
        groupers=groupers,
        cast_to_datetime=True,
        format="mixed",
        **events_temporal_params,
    )
    .call()
)


# %% [markdown]
# ## Filter events and get balloon sighting records

# %%
# parameters

filter_balloon_events_params = dict()

# %%
# call the task


filter_balloon_events = (
    filter_df.set_task_instance_id("filter_balloon_events")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        column_name="event_type",
        op="equal",
        value="balloon_landing",
        df=events_temporal,
        reset_index=False,
        **filter_balloon_events_params,
    )
    .call()
)


# %% [markdown]
# ## Filter events and get airstrip operation records

# %%
# parameters

filter_airstrip_operations_params = dict()

# %%
# call the task


filter_airstrip_operations = (
    filter_df.set_task_instance_id("filter_airstrip_operations")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        column_name="event_type",
        op="equal",
        value="airstrip_operations",
        df=events_temporal,
        reset_index=False,
        **filter_airstrip_operations_params,
    )
    .call()
)


# %% [markdown]
# ## Filter events and get airstrip maintenance records

# %%
# parameters

filter_airstrip_maintenance_params = dict()

# %%
# call the task


filter_airstrip_maintenance = (
    filter_df.set_task_instance_id("filter_airstrip_maintenance")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        column_name="event_type",
        op="equal",
        value="airstrip_maintenance",
        df=events_temporal,
        reset_index=False,
        **filter_airstrip_maintenance_params,
    )
    .call()
)


# %% [markdown]
# ## Filter events and get airline complaint records

# %%
# parameters

filter_airline_complaints_params = dict()

# %%
# call the task


filter_airline_complaints = (
    filter_df.set_task_instance_id("filter_airline_complaints")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        column_name="event_type",
        op="equal",
        value="airline_complaint",
        df=events_temporal,
        reset_index=False,
        **filter_airline_complaints_params,
    )
    .call()
)


# %% [markdown]
# ## Process balloon event details

# %%
# parameters

process_balloon_details_params = dict()

# %%
# call the task


process_balloon_details = (
    process_events_details.set_task_instance_id("process_balloon_details")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=filter_balloon_events,
        client=er_client_name,
        map_to_titles=True,
        ordered=True,
        **process_balloon_details_params,
    )
    .call()
)


# %% [markdown]
# ## Normalize balloon event details values

# %%
# parameters

normalize_balloon_values_params = dict()

# %%
# call the task


normalize_balloon_values = (
    normalize_json_column.set_task_instance_id("normalize_balloon_values")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        column="event_details",
        df=process_balloon_details,
        skip_if_not_exists=True,
        sort_columns=True,
        **normalize_balloon_values_params,
    )
    .call()
)


# %% [markdown]
# ## Drop column prefix from balloon event details s

# %%
# parameters

drop_balloon_prefix_params = dict()

# %%
# call the task


drop_balloon_prefix = (
    drop_column_prefix.set_task_instance_id("drop_balloon_prefix")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=normalize_balloon_values,
        prefix="event_details__",
        duplicate_strategy="keep_original",
        **drop_balloon_prefix_params,
    )
    .call()
)


# %% [markdown]
# ## Process airstrip operation event details

# %%
# parameters

process_airstrip_details_params = dict()

# %%
# call the task


process_airstrip_details = (
    process_events_details.set_task_instance_id("process_airstrip_details")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=filter_airstrip_operations,
        client=er_client_name,
        map_to_titles=True,
        ordered=True,
        **process_airstrip_details_params,
    )
    .call()
)


# %% [markdown]
# ## Normalize airstrip operation event details values

# %%
# parameters

normalize_airstrip_op_values_params = dict()

# %%
# call the task


normalize_airstrip_op_values = (
    normalize_json_column.set_task_instance_id("normalize_airstrip_op_values")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        column="event_details",
        df=process_airstrip_details,
        skip_if_not_exists=True,
        sort_columns=True,
        **normalize_airstrip_op_values_params,
    )
    .call()
)


# %% [markdown]
# ## Drop column prefix from airstrip operation event details

# %%
# parameters

drop_airstrip_op_prefix_params = dict()

# %%
# call the task


drop_airstrip_op_prefix = (
    drop_column_prefix.set_task_instance_id("drop_airstrip_op_prefix")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=normalize_airstrip_op_values,
        prefix="event_details__",
        duplicate_strategy="keep_original",
        **drop_airstrip_op_prefix_params,
    )
    .call()
)


# %% [markdown]
# ## Process airstrip maintenance event details

# %%
# parameters

process_airstrip_maint_details_params = dict()

# %%
# call the task


process_airstrip_maint_details = (
    process_events_details.set_task_instance_id("process_airstrip_maint_details")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=filter_airstrip_maintenance,
        client=er_client_name,
        map_to_titles=True,
        ordered=True,
        **process_airstrip_maint_details_params,
    )
    .call()
)


# %% [markdown]
# ## Normalize airstrip maintenance event details values

# %%
# parameters

normalize_airstrip_maint_vals_params = dict()

# %%
# call the task


normalize_airstrip_maint_vals = (
    normalize_json_column.set_task_instance_id("normalize_airstrip_maint_vals")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        column="event_details",
        df=process_airstrip_maint_details,
        skip_if_not_exists=True,
        sort_columns=True,
        **normalize_airstrip_maint_vals_params,
    )
    .call()
)


# %% [markdown]
# ## Drop column prefix from airstrip maintenance event details

# %%
# parameters

drop_airstrip_maintenance_prefix_params = dict()

# %%
# call the task


drop_airstrip_maintenance_prefix = (
    drop_column_prefix.set_task_instance_id("drop_airstrip_maintenance_prefix")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=normalize_airstrip_maint_vals,
        prefix="event_details__",
        duplicate_strategy="keep_original",
        **drop_airstrip_maintenance_prefix_params,
    )
    .call()
)


# %% [markdown]
# ## Process airline complaint event details

# %%
# parameters

process_airline_comp_details_params = dict()

# %%
# call the task


process_airline_comp_details = (
    process_events_details.set_task_instance_id("process_airline_comp_details")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=filter_airline_complaints,
        client=er_client_name,
        map_to_titles=True,
        ordered=True,
        **process_airline_comp_details_params,
    )
    .call()
)


# %% [markdown]
# ## Normalize airline complaint event details values

# %%
# parameters

normalize_airline_comp_vals_params = dict()

# %%
# call the task


normalize_airline_comp_vals = (
    normalize_json_column.set_task_instance_id("normalize_airline_comp_vals")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        column="event_details",
        df=process_airline_comp_details,
        skip_if_not_exists=True,
        sort_columns=True,
        **normalize_airline_comp_vals_params,
    )
    .call()
)


# %% [markdown]
# ## Drop column prefix from airline complaint event details

# %%
# parameters

drop_airline_complaint_prefix_params = dict()

# %%
# call the task


drop_airline_complaint_prefix = (
    drop_column_prefix.set_task_instance_id("drop_airline_complaint_prefix")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=normalize_airline_comp_vals,
        prefix="event_details__",
        duplicate_strategy="keep_original",
        **drop_airline_complaint_prefix_params,
    )
    .call()
)


# %% [markdown]
# ## Map balloon columns

# %%
# parameters

map_balloon_columns_params = dict()

# %%
# call the task


map_balloon_columns = (
    map_columns.set_task_instance_id("map_balloon_columns")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=drop_balloon_prefix,
        drop_columns=[],
        retain_columns=[
            "date",
            "Balloon Company",
            "Where are clients staying?",
            "# of passengers",
        ],
        rename_columns={
            "Balloon Company": "balloon_company",
            "Where are clients staying?": "where_are_clients_staying",
            "# of passengers": "no_of_passengers",
        },
        raise_if_not_found=False,
        **map_balloon_columns_params,
    )
    .call()
)


# %% [markdown]
# ## Remove brackets from columns in balloon events

# %%
# parameters

remove_balloon_brackets_params = dict()

# %%
# call the task


remove_balloon_brackets = (
    remove_brackets_from_column.set_task_instance_id("remove_balloon_brackets")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=map_balloon_columns,
        columns=["balloon_company", "where_are_clients_staying"],
        **remove_balloon_brackets_params,
    )
    .call()
)


# %% [markdown]
# ## Persist balloon landing summary table

# %%
# parameters

persist_balloon_landing_params = dict()

# %%
# call the task


persist_balloon_landing = (
    persist_df.set_task_instance_id("persist_balloon_landing")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filetype="csv",
        df=remove_balloon_brackets,
        filename="balloon_landing_summary_table",
        **persist_balloon_landing_params,
    )
    .call()
)


# %% [markdown]
# ## Map airstrip operation columns

# %%
# parameters

map_airstrip_op_columns_params = dict()

# %%
# call the task


map_airstrip_op_columns = (
    map_columns.set_task_instance_id("map_airstrip_op_columns")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=drop_airstrip_op_prefix,
        drop_columns=[],
        retain_columns=[],
        rename_columns={
            "Airline": "airline",
            "Arrival or departure": "arrival_departure",
            "Attendant": "attendant",
            "Camp/Lodge": "camp_lodge",
            "Number of clients": "no_of_clients",
        },
        raise_if_not_found=False,
        **map_airstrip_op_columns_params,
    )
    .call()
)


# %% [markdown]
# ## Remove brackets from columns in airstrip operation events

# %%
# parameters

remove_airstrip_op_brackets_params = dict()

# %%
# call the task


remove_airstrip_op_brackets = (
    remove_brackets_from_column.set_task_instance_id("remove_airstrip_op_brackets")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=map_airstrip_op_columns,
        columns=["airline", "arrival_departure", "attendant", "camp_lodge"],
        **remove_airstrip_op_brackets_params,
    )
    .call()
)


# %% [markdown]
# ## Replace missing values in camp_lodge column with other

# %%
# parameters

replace_airstrip_op_nulls_params = dict()

# %%
# call the task


replace_airstrip_op_nulls = (
    replace_missing_with_label.set_task_instance_id("replace_airstrip_op_nulls")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=remove_airstrip_op_brackets,
        columns=["camp_lodge"],
        label="other",
        **replace_airstrip_op_nulls_params,
    )
    .call()
)


# %% [markdown]
# ## Convert columns to integer

# %%
# parameters

convert_airstrip_op_ints_params = dict()

# %%
# call the task


convert_airstrip_op_ints = (
    convert_to_int.set_task_instance_id("convert_airstrip_op_ints")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=replace_airstrip_op_nulls,
        columns=["no_of_clients"],
        errors="coerce",
        fill_value=0,
        inplace=False,
        **convert_airstrip_op_ints_params,
    )
    .call()
)


# %% [markdown]
# ## Capitalize text in camp_lodge column

# %%
# parameters

capitalize_camp_lodge_params = dict()

# %%
# call the task


capitalize_camp_lodge = (
    capitalize_text.set_task_instance_id("capitalize_camp_lodge")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=convert_airstrip_op_ints, column="camp_lodge", **capitalize_camp_lodge_params
    )
    .call()
)


# %% [markdown]
# ## Airstrip operation events summary table

# %%
# parameters

airstrip_op_summary_table_params = dict()

# %%
# call the task


airstrip_op_summary_table = (
    summarize_df.set_task_instance_id("airstrip_op_summary_table")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=capitalize_camp_lodge,
        groupby_cols=["camp_lodge", "arrival_departure"],
        summary_params=[
            {
                "display_name": "no_of_clients",
                "aggregator": "sum",
                "column": "no_of_clients",
                "decimal_places": 0,
            }
        ],
        reset_index=True,
        **airstrip_op_summary_table_params,
    )
    .call()
)


# %% [markdown]
# ## Pivot airstrip operations summary table

# %%
# parameters

pivot_airstrip_ops_params = dict()

# %%
# call the task


pivot_airstrip_ops = (
    pivot_df.set_task_instance_id("pivot_airstrip_ops")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=airstrip_op_summary_table,
        index_col="camp_lodge",
        columns_col="arrival_departure",
        values_col="no_of_clients",
        reset_idx=True,
        **pivot_airstrip_ops_params,
    )
    .call()
)


# %% [markdown]
# ## Convert airstrip pivot table values to int

# %%
# parameters

convert_pivot_int_params = dict()

# %%
# call the task


convert_pivot_int = (
    convert_to_int.set_task_instance_id("convert_pivot_int")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=pivot_airstrip_ops,
        columns=["arrival", "departure"],
        errors="coerce",
        fill_value=0,
        inplace=False,
        **convert_pivot_int_params,
    )
    .call()
)


# %% [markdown]
# ## Persist airstrip operations summary table

# %%
# parameters

persist_airstrip_operations_params = dict()

# %%
# call the task


persist_airstrip_operations = (
    persist_df.set_task_instance_id("persist_airstrip_operations")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filetype="csv",
        df=convert_pivot_int,
        filename="airstrip_operations_summary_table",
        **persist_airstrip_operations_params,
    )
    .call()
)


# %% [markdown]
# ## Map airstrip maintenace columns

# %%
# parameters

map_airstrip_maintenance_params = dict()

# %%
# call the task


map_airstrip_maintenance = (
    map_columns.set_task_instance_id("map_airstrip_maintenance")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=drop_airstrip_maintenance_prefix,
        drop_columns=[],
        retain_columns=["date", "Maintenance type"],
        rename_columns={"Maintenance type": "maintenance_type"},
        raise_if_not_found=False,
        **map_airstrip_maintenance_params,
    )
    .call()
)


# %% [markdown]
# ## Persist airstrip maintenace summary table

# %%
# parameters

persist_airstrip_maintenance_params = dict()

# %%
# call the task


persist_airstrip_maintenance = (
    persist_df.set_task_instance_id("persist_airstrip_maintenance")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filetype="csv",
        df=map_airstrip_maintenance,
        filename="airstrip_maintenance_summary_table",
        **persist_airstrip_maintenance_params,
    )
    .call()
)


# %% [markdown]
# ## MNC event report dashboard

# %%
# parameters

mnc_events_dashboard_params = dict(
    warning=...,
)

# %%
# call the task


mnc_events_dashboard = (
    gather_dashboard.set_task_instance_id("mnc_events_dashboard")
    .handle_errors()
    .with_tracing()
    .partial(
        details=workflow_details,
        widgets=[],
        time_range=time_range,
        groupers=groupers,
        **mnc_events_dashboard_params,
    )
    .call()
)
