# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details


# ruff: noqa: E402

# %% [markdown]
# # Mnc Logistics Report
# TODO: top level description

# %% [markdown]
# ## Imports

import os

from ecoscope_workflows_core.tasks.config import (
    set_workflow_details as set_workflow_details,
)
from ecoscope_workflows_core.tasks.filter import set_time_range as set_time_range
from ecoscope_workflows_core.tasks.groupby import set_groupers as set_groupers
from ecoscope_workflows_core.tasks.io import set_er_connection as set_er_connection
from ecoscope_workflows_core.tasks.results import gather_dashboard as gather_dashboard
from ecoscope_workflows_core.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope_workflows_core.tasks.skip import any_is_empty_df as any_is_empty_df
from ecoscope_workflows_core.tasks.transformation import (
    add_temporal_index as add_temporal_index,
)
from ecoscope_workflows_core.tasks.transformation import (
    extract_column_as_type as extract_column_as_type,
)
from ecoscope_workflows_core.tasks.transformation import filter_df as filter_df
from ecoscope_workflows_core.tasks.transformation import map_columns as map_columns
from ecoscope_workflows_ext_ecoscope.tasks.analysis import summarize_df as summarize_df
from ecoscope_workflows_ext_ecoscope.tasks.io import get_events as get_events
from ecoscope_workflows_ext_ecoscope.tasks.io import persist_df as persist_df
from ecoscope_workflows_ext_ecoscope.tasks.transformation import (
    normalize_json_column as normalize_json_column,
)
from ecoscope_workflows_ext_mnc.tasks import capitalize_text as capitalize_text
from ecoscope_workflows_ext_mnc.tasks import convert_to_int as convert_to_int
from ecoscope_workflows_ext_mnc.tasks import filter_columns as filter_columns
from ecoscope_workflows_ext_mnc.tasks import pivot_df as pivot_df
from ecoscope_workflows_ext_mnc.tasks import (
    remove_brackets_from_column as remove_brackets_from_column,
)
from ecoscope_workflows_ext_mnc.tasks import (
    replace_missing_with_label as replace_missing_with_label,
)
from ecoscope_workflows_ext_mnc.tasks import transform_columns as transform_columns

# %% [markdown]
# ## Set workflow details

# %%
# parameters

workflow_details_params = dict(
    name=...,
    description=...,
    image_url=...,
)

# %%
# call the task


workflow_details = (
    set_workflow_details.set_task_instance_id("workflow_details")
    .handle_errors()
    .with_tracing()
    .partial(**workflow_details_params)
    .call()
)


# %% [markdown]
# ## Time range

# %%
# parameters

time_range_params = dict(
    since=...,
    until=...,
    timezone=...,
    time_format=...,
)

# %%
# call the task


time_range = (
    set_time_range.set_task_instance_id("time_range")
    .handle_errors()
    .with_tracing()
    .partial(**time_range_params)
    .call()
)


# %% [markdown]
# ## Set groupers

# %%
# parameters

groupers_params = dict()

# %%
# call the task


groupers = (
    set_groupers.set_task_instance_id("groupers")
    .handle_errors()
    .with_tracing()
    .partial(groupers=[], **groupers_params)
    .call()
)


# %% [markdown]
# ## Connect to ER

# %%
# parameters

er_client_name_params = dict(
    data_source=...,
)

# %%
# call the task


er_client_name = (
    set_er_connection.set_task_instance_id("er_client_name")
    .handle_errors()
    .with_tracing()
    .partial(**er_client_name_params)
    .call()
)


# %% [markdown]
# ## Retrieve all events

# %%
# parameters

get_events_data_params = dict()

# %%
# call the task


get_events_data = (
    get_events.set_task_instance_id("get_events_data")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        client=er_client_name,
        time_range=time_range,
        event_columns=[
            "id",
            "time",
            "event_type",
            "event_category",
            "reported_by",
            "serial_number",
            "geometry",
            "created_at",
            "event_details",
            "patrols",
        ],
        event_types=[],
        raise_on_empty=True,
        include_details=True,
        include_updates=False,
        include_related_events=False,
        include_null_geometry=False,
        include_display_values=False,
        **get_events_data_params,
    )
    .call()
)


# %% [markdown]
# ## Extract date from events data

# %%
# parameters

extract_event_date_params = dict()

# %%
# call the task


extract_event_date = (
    extract_column_as_type.set_task_instance_id("extract_event_date")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=get_events_data,
        column_name="time",
        output_type="date",
        output_column_name="date",
        **extract_event_date_params,
    )
    .call()
)


# %% [markdown]
# ## Add temporal index on events

# %%
# parameters

events_temporal_params = dict()

# %%
# call the task


events_temporal = (
    add_temporal_index.set_task_instance_id("events_temporal")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=extract_event_date,
        time_col="date",
        groupers=groupers,
        cast_to_datetime=True,
        format="mixed",
        **events_temporal_params,
    )
    .call()
)


# %% [markdown]
# ## Filter events and get balloon sighting records

# %%
# parameters

filter_balloon_events_params = dict()

# %%
# call the task


filter_balloon_events = (
    filter_df.set_task_instance_id("filter_balloon_events")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        column_name="event_type",
        op="equal",
        value="balloon_landing",
        df=events_temporal,
        reset_index=False,
        **filter_balloon_events_params,
    )
    .call()
)


# %% [markdown]
# ## Normalize event details columns

# %%
# parameters

normalize_balloon_values_params = dict()

# %%
# call the task


normalize_balloon_values = (
    normalize_json_column.set_task_instance_id("normalize_balloon_values")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        column="event_details",
        df=filter_balloon_events,
        skip_if_not_exists=True,
        sort_columns=True,
        **normalize_balloon_values_params,
    )
    .call()
)


# %% [markdown]
# ## Rename balloon columns

# %%
# parameters

rename_balloon_boma_params = dict()

# %%
# call the task


rename_balloon_boma = (
    transform_columns.set_task_instance_id("rename_balloon_boma")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        drop_columns=[],
        retain_columns=[],
        rename_columns={
            "event_details__of_passengers": "no_of_passengers",
            "event_details__balloon_company": "balloon_company",
            "event_details__where_are_clients_staying": "lodge",
        },
        skip_missing_rename=True,
        required_columns=[
            "event_details__of_passengers",
            "event_details__balloon_company",
            "date",
            "event_details__where_are_clients_staying",
        ],
        df=normalize_balloon_values,
        **rename_balloon_boma_params,
    )
    .call()
)


# %% [markdown]
# ## Remove brackets from column in balloon landing events

# %%
# parameters

remove_balloon_brackets_params = dict()

# %%
# call the task


remove_balloon_brackets = (
    remove_brackets_from_column.set_task_instance_id("remove_balloon_brackets")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=rename_balloon_boma,
        columns=["lodge", "balloon_company"],
        **remove_balloon_brackets_params,
    )
    .call()
)


# %% [markdown]
# ## Replace lodge nulls with other

# %%
# parameters

replace_lodge_nulls_params = dict()

# %%
# call the task


replace_lodge_nulls = (
    replace_missing_with_label.set_task_instance_id("replace_lodge_nulls")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=remove_balloon_brackets,
        columns=["lodge"],
        label="other",
        **replace_lodge_nulls_params,
    )
    .call()
)


# %% [markdown]
# ## Convert no_of_passengers col to int

# %%
# parameters

convert_passengers_int_params = dict()

# %%
# call the task


convert_passengers_int = (
    convert_to_int.set_task_instance_id("convert_passengers_int")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=replace_lodge_nulls,
        columns=["no_of_passengers"],
        errors="coerce",
        fill_value=0,
        inplace=False,
        **convert_passengers_int_params,
    )
    .call()
)


# %% [markdown]
# ## Generate balloon summary tables

# %%
# parameters

generate_balloon_table_params = dict()

# %%
# call the task


generate_balloon_table = (
    summarize_df.set_task_instance_id("generate_balloon_table")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        groupby_cols=["date", "balloon_company", "lodge"],
        summary_params=[
            {
                "display_name": "no_of_passengers",
                "aggregator": "sum",
                "column": "no_of_passengers",
            }
        ],
        reset_index=True,
        df=convert_passengers_int,
        **generate_balloon_table_params,
    )
    .call()
)


# %% [markdown]
# ## Capitalize balloon co

# %%
# parameters

capitalize_balloon_co_params = dict()

# %%
# call the task


capitalize_balloon_co = (
    capitalize_text.set_task_instance_id("capitalize_balloon_co")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=generate_balloon_table,
        column="balloon_company",
        **capitalize_balloon_co_params,
    )
    .call()
)


# %% [markdown]
# ## Capitalize lodge

# %%
# parameters

capitalize_lodge_params = dict()

# %%
# call the task


capitalize_lodge = (
    capitalize_text.set_task_instance_id("capitalize_lodge")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(df=capitalize_balloon_co, column="lodge", **capitalize_lodge_params)
    .call()
)


# %% [markdown]
# ## Persist balloon summary table

# %%
# parameters

persist_balloon_summary_params = dict()

# %%
# call the task


persist_balloon_summary = (
    persist_df.set_task_instance_id("persist_balloon_summary")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filetype="csv",
        df=capitalize_lodge,
        filename="balloon_landing_by_date",
        **persist_balloon_summary_params,
    )
    .call()
)


# %% [markdown]
# ## Filter events and get airstrip operations records

# %%
# parameters

filter_airstrip_events_params = dict()

# %%
# call the task


filter_airstrip_events = (
    filter_df.set_task_instance_id("filter_airstrip_events")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        column_name="event_type",
        op="equal",
        value="airstrip_operations",
        df=events_temporal,
        reset_index=False,
        **filter_airstrip_events_params,
    )
    .call()
)


# %% [markdown]
# ## Normalize airstrip_operations

# %%
# parameters

normalize_airstrip_values_params = dict()

# %%
# call the task


normalize_airstrip_values = (
    normalize_json_column.set_task_instance_id("normalize_airstrip_values")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        column="event_details",
        df=filter_airstrip_events,
        skip_if_not_exists=True,
        sort_columns=True,
        **normalize_airstrip_values_params,
    )
    .call()
)


# %% [markdown]
# ## Rename airstrip information columns

# %%
# parameters

rename_airstrip_params = dict()

# %%
# call the task


rename_airstrip = (
    map_columns.set_task_instance_id("rename_airstrip")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        raise_if_not_found=True,
        drop_columns=[],
        retain_columns=[],
        rename_columns={
            "event_details__guide": "guide",
            "event_details__airline": "airline",
            "event_details__attendant": "attendant",
            "event_details__camplodge": "camp_lodge",
            "event_details__flight_number": "flight_number",
            "event_details__number_of_clients": "number_of_clients",
            "event_details__arrival_or_departure": "arrival_or_departure",
        },
        df=normalize_airstrip_values,
        **rename_airstrip_params,
    )
    .call()
)


# %% [markdown]
# ## Remove brackets from column in airstrip events

# %%
# parameters

remove_air_brackets_params = dict()

# %%
# call the task


remove_air_brackets = (
    remove_brackets_from_column.set_task_instance_id("remove_air_brackets")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=rename_airstrip,
        columns=["airline", "attendant", "camp_lodge", "arrival_or_departure"],
        **remove_air_brackets_params,
    )
    .call()
)


# %% [markdown]
# ## Replace camp_lodge nulls with other

# %%
# parameters

replace_camp_lodge_nulls_params = dict()

# %%
# call the task


replace_camp_lodge_nulls = (
    replace_missing_with_label.set_task_instance_id("replace_camp_lodge_nulls")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=remove_air_brackets,
        columns=["camp_lodge"],
        label="other",
        **replace_camp_lodge_nulls_params,
    )
    .call()
)


# %% [markdown]
# ## Convert number_of_clients col to int

# %%
# parameters

convert_clients_int_params = dict()

# %%
# call the task


convert_clients_int = (
    convert_to_int.set_task_instance_id("convert_clients_int")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=replace_camp_lodge_nulls,
        columns=["number_of_clients"],
        errors="coerce",
        fill_value=0,
        inplace=False,
        **convert_clients_int_params,
    )
    .call()
)


# %% [markdown]
# ## Convert airstrip lodge to sentence case

# %%
# parameters

lodge_scase_params = dict()

# %%
# call the task


lodge_scase = (
    capitalize_text.set_task_instance_id("lodge_scase")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(df=convert_clients_int, column="camp_lodge", **lodge_scase_params)
    .call()
)


# %% [markdown]
# ## Airstrip operations summary table

# %%
# parameters

airstrip_summary_table_params = dict()

# %%
# call the task


airstrip_summary_table = (
    summarize_df.set_task_instance_id("airstrip_summary_table")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=lodge_scase,
        groupby_cols=["camp_lodge", "arrival_or_departure"],
        summary_params=[
            {
                "display_name": "no_of_passengers",
                "aggregator": "sum",
                "column": "number_of_clients",
                "decimal_places": 0,
            }
        ],
        reset_index=True,
        **airstrip_summary_table_params,
    )
    .call()
)


# %% [markdown]
# ## Pivot summary table

# %%
# parameters

pivot_airstrip_table_params = dict()

# %%
# call the task


pivot_airstrip_table = (
    pivot_df.set_task_instance_id("pivot_airstrip_table")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=airstrip_summary_table,
        index_col="camp_lodge",
        columns_col="arrival_or_departure",
        values_col="no_of_passengers",
        reset_idx=True,
        **pivot_airstrip_table_params,
    )
    .call()
)


# %% [markdown]
# ## Perist airstrip operations summary table

# %%
# parameters

persist_airstrip_summary_params = dict()

# %%
# call the task


persist_airstrip_summary = (
    persist_df.set_task_instance_id("persist_airstrip_summary")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filetype="csv",
        df=pivot_airstrip_table,
        filename="airstrip_arrivals_and_departure",
        **persist_airstrip_summary_params,
    )
    .call()
)


# %% [markdown]
# ## Filter events and get airstrip maintenance records

# %%
# parameters

filter_am_events_params = dict()

# %%
# call the task


filter_am_events = (
    filter_df.set_task_instance_id("filter_am_events")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        column_name="event_type",
        op="equal",
        value="airstrip_maintenance",
        df=events_temporal,
        reset_index=False,
        **filter_am_events_params,
    )
    .call()
)


# %% [markdown]
# ## Normalize event details columns

# %%
# parameters

normalize_am_values_params = dict()

# %%
# call the task


normalize_am_values = (
    normalize_json_column.set_task_instance_id("normalize_am_values")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        column="event_details",
        df=filter_am_events,
        skip_if_not_exists=True,
        sort_columns=True,
        **normalize_am_values_params,
    )
    .call()
)


# %% [markdown]
# ## Rename airstrip_maintenance columns

# %%
# parameters

rename_am_params = dict()

# %%
# call the task


rename_am = (
    transform_columns.set_task_instance_id("rename_am")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        drop_columns=[],
        retain_columns=[],
        rename_columns={"event_details__maintenance_type": "activity"},
        skip_missing_rename=True,
        required_columns=["event_details__maintenance_type"],
        df=normalize_am_values,
        **rename_am_params,
    )
    .call()
)


# %% [markdown]
# ## Filter out columns

# %%
# parameters

filter_cols_params = dict()

# %%
# call the task


filter_cols = (
    filter_columns.set_task_instance_id("filter_cols")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=rename_am, columns=["date", "activity"], exclude=[], **filter_cols_params
    )
    .call()
)


# %% [markdown]
# ## Capitalize activity column

# %%
# parameters

capitalize_activity_col_params = dict()

# %%
# call the task


capitalize_activity_col = (
    capitalize_text.set_task_instance_id("capitalize_activity_col")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(df=filter_cols, column="activity", **capitalize_activity_col_params)
    .call()
)


# %% [markdown]
# ## Persist airstrip maintenance table

# %%
# parameters

persist_air_maintenance_params = dict()

# %%
# call the task


persist_air_maintenance = (
    persist_df.set_task_instance_id("persist_air_maintenance")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filetype="csv",
        df=capitalize_activity_col,
        filename="airstrip_maintenance_table",
        **persist_air_maintenance_params,
    )
    .call()
)


# %% [markdown]
# ## MNC event report dashboard

# %%
# parameters

mnc_events_dashboard_params = dict(
    warning=...,
)

# %%
# call the task


mnc_events_dashboard = (
    gather_dashboard.set_task_instance_id("mnc_events_dashboard")
    .handle_errors()
    .with_tracing()
    .partial(
        details=workflow_details,
        widgets=[],
        time_range=time_range,
        groupers=groupers,
        **mnc_events_dashboard_params,
    )
    .call()
)
