# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details
import json
import os

from ecoscope_workflows_core.graph import DependsOn, Graph, Node
from ecoscope_workflows_core.tasks.config import (
    set_workflow_details as set_workflow_details,
)
from ecoscope_workflows_core.tasks.filter import set_time_range as set_time_range
from ecoscope_workflows_core.tasks.groupby import set_groupers as set_groupers
from ecoscope_workflows_core.tasks.io import set_er_connection as set_er_connection
from ecoscope_workflows_core.tasks.results import gather_dashboard as gather_dashboard
from ecoscope_workflows_core.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope_workflows_core.tasks.skip import any_is_empty_df as any_is_empty_df
from ecoscope_workflows_core.tasks.transformation import (
    add_temporal_index as add_temporal_index,
)
from ecoscope_workflows_core.tasks.transformation import (
    extract_column_as_type as extract_column_as_type,
)
from ecoscope_workflows_core.tasks.transformation import filter_df as filter_df
from ecoscope_workflows_core.tasks.transformation import map_columns as map_columns
from ecoscope_workflows_ext_ecoscope.tasks.analysis import summarize_df as summarize_df
from ecoscope_workflows_ext_ecoscope.tasks.io import get_events as get_events
from ecoscope_workflows_ext_ecoscope.tasks.io import persist_df as persist_df
from ecoscope_workflows_ext_ecoscope.tasks.transformation import (
    normalize_json_column as normalize_json_column,
)
from ecoscope_workflows_ext_mnc.tasks import capitalize_text as capitalize_text
from ecoscope_workflows_ext_mnc.tasks import convert_to_int as convert_to_int
from ecoscope_workflows_ext_mnc.tasks import filter_columns as filter_columns
from ecoscope_workflows_ext_mnc.tasks import pivot_df as pivot_df
from ecoscope_workflows_ext_mnc.tasks import (
    remove_brackets_from_column as remove_brackets_from_column,
)
from ecoscope_workflows_ext_mnc.tasks import (
    replace_missing_with_label as replace_missing_with_label,
)
from ecoscope_workflows_ext_mnc.tasks import transform_columns as transform_columns

from ..params import Params


def main(params: Params):
    params_dict = json.loads(params.model_dump_json(exclude_unset=True))

    dependencies = {
        "workflow_details": [],
        "time_range": [],
        "groupers": [],
        "er_client_name": [],
        "get_events_data": ["er_client_name", "time_range"],
        "extract_event_date": ["get_events_data"],
        "events_temporal": ["extract_event_date", "groupers"],
        "filter_balloon_events": ["events_temporal"],
        "normalize_balloon_values": ["filter_balloon_events"],
        "rename_balloon_boma": ["normalize_balloon_values"],
        "remove_balloon_brackets": ["rename_balloon_boma"],
        "replace_lodge_nulls": ["remove_balloon_brackets"],
        "convert_passengers_int": ["replace_lodge_nulls"],
        "generate_balloon_table": ["convert_passengers_int"],
        "capitalize_balloon_co": ["generate_balloon_table"],
        "capitalize_lodge": ["capitalize_balloon_co"],
        "persist_balloon_summary": ["capitalize_lodge"],
        "filter_airstrip_events": ["events_temporal"],
        "normalize_airstrip_values": ["filter_airstrip_events"],
        "rename_airstrip": ["normalize_airstrip_values"],
        "remove_air_brackets": ["rename_airstrip"],
        "replace_camp_lodge_nulls": ["remove_air_brackets"],
        "convert_clients_int": ["replace_camp_lodge_nulls"],
        "lodge_scase": ["convert_clients_int"],
        "airstrip_summary_table": ["lodge_scase"],
        "pivot_airstrip_table": ["airstrip_summary_table"],
        "persist_airstrip_summary": ["pivot_airstrip_table"],
        "filter_am_events": ["events_temporal"],
        "normalize_am_values": ["filter_am_events"],
        "rename_am": ["normalize_am_values"],
        "filter_cols": ["rename_am"],
        "capitalize_activity_col": ["filter_cols"],
        "persist_air_maintenance": ["capitalize_activity_col"],
        "mnc_events_dashboard": ["workflow_details", "time_range", "groupers"],
    }

    nodes = {
        "workflow_details": Node(
            async_task=set_workflow_details.validate()
            .set_task_instance_id("workflow_details")
            .handle_errors()
            .with_tracing()
            .set_executor("lithops"),
            partial=(params_dict.get("workflow_details") or {}),
            method="call",
        ),
        "time_range": Node(
            async_task=set_time_range.validate()
            .set_task_instance_id("time_range")
            .handle_errors()
            .with_tracing()
            .set_executor("lithops"),
            partial=(params_dict.get("time_range") or {}),
            method="call",
        ),
        "groupers": Node(
            async_task=set_groupers.validate()
            .set_task_instance_id("groupers")
            .handle_errors()
            .with_tracing()
            .set_executor("lithops"),
            partial={} | (params_dict.get("groupers") or {}),
            method="call",
        ),
        "er_client_name": Node(
            async_task=set_er_connection.validate()
            .set_task_instance_id("er_client_name")
            .handle_errors()
            .with_tracing()
            .set_executor("lithops"),
            partial=(params_dict.get("er_client_name") or {}),
            method="call",
        ),
        "get_events_data": Node(
            async_task=get_events.validate()
            .set_task_instance_id("get_events_data")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "client": DependsOn("er_client_name"),
                "time_range": DependsOn("time_range"),
                "event_columns": [
                    "id",
                    "time",
                    "event_type",
                    "event_category",
                    "reported_by",
                    "serial_number",
                    "geometry",
                    "created_at",
                    "event_details",
                    "patrols",
                ],
                "raise_on_empty": True,
                "include_details": True,
                "include_updates": False,
                "include_related_events": False,
                "include_null_geometry": False,
                "include_display_values": False,
            }
            | (params_dict.get("get_events_data") or {}),
            method="call",
        ),
        "extract_event_date": Node(
            async_task=extract_column_as_type.validate()
            .set_task_instance_id("extract_event_date")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("get_events_data"),
                "column_name": "time",
                "output_type": "date",
                "output_column_name": "date",
            }
            | (params_dict.get("extract_event_date") or {}),
            method="call",
        ),
        "events_temporal": Node(
            async_task=add_temporal_index.validate()
            .set_task_instance_id("events_temporal")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("extract_event_date"),
                "time_col": "date",
                "groupers": DependsOn("groupers"),
                "cast_to_datetime": True,
                "format": "mixed",
            }
            | (params_dict.get("events_temporal") or {}),
            method="call",
        ),
        "filter_balloon_events": Node(
            async_task=filter_df.validate()
            .set_task_instance_id("filter_balloon_events")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "column_name": "event_type",
                "op": "equal",
                "value": "balloon_landing",
                "df": DependsOn("events_temporal"),
                "reset_index": False,
            }
            | (params_dict.get("filter_balloon_events") or {}),
            method="call",
        ),
        "normalize_balloon_values": Node(
            async_task=normalize_json_column.validate()
            .set_task_instance_id("normalize_balloon_values")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "column": "event_details",
                "df": DependsOn("filter_balloon_events"),
                "skip_if_not_exists": True,
                "sort_columns": True,
            }
            | (params_dict.get("normalize_balloon_values") or {}),
            method="call",
        ),
        "rename_balloon_boma": Node(
            async_task=transform_columns.validate()
            .set_task_instance_id("rename_balloon_boma")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "rename_columns": {
                    "event_details__of_passengers": "no_of_passengers",
                    "event_details__balloon_company": "balloon_company",
                    "event_details__where_are_clients_staying": "lodge",
                },
                "skip_missing_rename": True,
                "required_columns": [
                    "event_details__of_passengers",
                    "event_details__balloon_company",
                    "date",
                    "event_details__where_are_clients_staying",
                ],
                "df": DependsOn("normalize_balloon_values"),
            }
            | (params_dict.get("rename_balloon_boma") or {}),
            method="call",
        ),
        "remove_balloon_brackets": Node(
            async_task=remove_brackets_from_column.validate()
            .set_task_instance_id("remove_balloon_brackets")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("rename_balloon_boma"),
                "columns": [
                    "lodge",
                    "balloon_company",
                ],
            }
            | (params_dict.get("remove_balloon_brackets") or {}),
            method="call",
        ),
        "replace_lodge_nulls": Node(
            async_task=replace_missing_with_label.validate()
            .set_task_instance_id("replace_lodge_nulls")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("remove_balloon_brackets"),
                "columns": [
                    "lodge",
                ],
                "label": "other",
            }
            | (params_dict.get("replace_lodge_nulls") or {}),
            method="call",
        ),
        "convert_passengers_int": Node(
            async_task=convert_to_int.validate()
            .set_task_instance_id("convert_passengers_int")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("replace_lodge_nulls"),
                "columns": [
                    "no_of_passengers",
                ],
                "errors": "coerce",
                "fill_value": 0,
                "inplace": False,
            }
            | (params_dict.get("convert_passengers_int") or {}),
            method="call",
        ),
        "generate_balloon_table": Node(
            async_task=summarize_df.validate()
            .set_task_instance_id("generate_balloon_table")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "groupby_cols": [
                    "date",
                    "balloon_company",
                    "lodge",
                ],
                "summary_params": [
                    {
                        "display_name": "no_of_passengers",
                        "aggregator": "sum",
                        "column": "no_of_passengers",
                    },
                ],
                "reset_index": True,
                "df": DependsOn("convert_passengers_int"),
            }
            | (params_dict.get("generate_balloon_table") or {}),
            method="call",
        ),
        "capitalize_balloon_co": Node(
            async_task=capitalize_text.validate()
            .set_task_instance_id("capitalize_balloon_co")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("generate_balloon_table"),
                "column": "balloon_company",
            }
            | (params_dict.get("capitalize_balloon_co") or {}),
            method="call",
        ),
        "capitalize_lodge": Node(
            async_task=capitalize_text.validate()
            .set_task_instance_id("capitalize_lodge")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("capitalize_balloon_co"),
                "column": "lodge",
            }
            | (params_dict.get("capitalize_lodge") or {}),
            method="call",
        ),
        "persist_balloon_summary": Node(
            async_task=persist_df.validate()
            .set_task_instance_id("persist_balloon_summary")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "filetype": "csv",
                "df": DependsOn("capitalize_lodge"),
                "filename": "balloon_landing_by_date",
            }
            | (params_dict.get("persist_balloon_summary") or {}),
            method="call",
        ),
        "filter_airstrip_events": Node(
            async_task=filter_df.validate()
            .set_task_instance_id("filter_airstrip_events")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "column_name": "event_type",
                "op": "equal",
                "value": "airstrip_operations",
                "df": DependsOn("events_temporal"),
                "reset_index": False,
            }
            | (params_dict.get("filter_airstrip_events") or {}),
            method="call",
        ),
        "normalize_airstrip_values": Node(
            async_task=normalize_json_column.validate()
            .set_task_instance_id("normalize_airstrip_values")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "column": "event_details",
                "df": DependsOn("filter_airstrip_events"),
                "skip_if_not_exists": True,
                "sort_columns": True,
            }
            | (params_dict.get("normalize_airstrip_values") or {}),
            method="call",
        ),
        "rename_airstrip": Node(
            async_task=map_columns.validate()
            .set_task_instance_id("rename_airstrip")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "raise_if_not_found": True,
                "rename_columns": {
                    "event_details__guide": "guide",
                    "event_details__airline": "airline",
                    "event_details__attendant": "attendant",
                    "event_details__camplodge": "camp_lodge",
                    "event_details__flight_number": "flight_number",
                    "event_details__number_of_clients": "number_of_clients",
                    "event_details__arrival_or_departure": "arrival_or_departure",
                },
                "df": DependsOn("normalize_airstrip_values"),
            }
            | (params_dict.get("rename_airstrip") or {}),
            method="call",
        ),
        "remove_air_brackets": Node(
            async_task=remove_brackets_from_column.validate()
            .set_task_instance_id("remove_air_brackets")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("rename_airstrip"),
                "columns": [
                    "airline",
                    "attendant",
                    "camp_lodge",
                    "arrival_or_departure",
                ],
            }
            | (params_dict.get("remove_air_brackets") or {}),
            method="call",
        ),
        "replace_camp_lodge_nulls": Node(
            async_task=replace_missing_with_label.validate()
            .set_task_instance_id("replace_camp_lodge_nulls")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("remove_air_brackets"),
                "columns": [
                    "camp_lodge",
                ],
                "label": "other",
            }
            | (params_dict.get("replace_camp_lodge_nulls") or {}),
            method="call",
        ),
        "convert_clients_int": Node(
            async_task=convert_to_int.validate()
            .set_task_instance_id("convert_clients_int")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("replace_camp_lodge_nulls"),
                "columns": [
                    "number_of_clients",
                ],
                "errors": "coerce",
                "fill_value": 0,
                "inplace": False,
            }
            | (params_dict.get("convert_clients_int") or {}),
            method="call",
        ),
        "lodge_scase": Node(
            async_task=capitalize_text.validate()
            .set_task_instance_id("lodge_scase")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("convert_clients_int"),
                "column": "camp_lodge",
            }
            | (params_dict.get("lodge_scase") or {}),
            method="call",
        ),
        "airstrip_summary_table": Node(
            async_task=summarize_df.validate()
            .set_task_instance_id("airstrip_summary_table")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("lodge_scase"),
                "groupby_cols": [
                    "camp_lodge",
                    "arrival_or_departure",
                ],
                "summary_params": [
                    {
                        "display_name": "no_of_passengers",
                        "aggregator": "sum",
                        "column": "number_of_clients",
                        "decimal_places": 0,
                    },
                ],
                "reset_index": True,
            }
            | (params_dict.get("airstrip_summary_table") or {}),
            method="call",
        ),
        "pivot_airstrip_table": Node(
            async_task=pivot_df.validate()
            .set_task_instance_id("pivot_airstrip_table")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("airstrip_summary_table"),
                "index_col": "camp_lodge",
                "columns_col": "arrival_or_departure",
                "values_col": "no_of_passengers",
                "reset_idx": True,
            }
            | (params_dict.get("pivot_airstrip_table") or {}),
            method="call",
        ),
        "persist_airstrip_summary": Node(
            async_task=persist_df.validate()
            .set_task_instance_id("persist_airstrip_summary")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "filetype": "csv",
                "df": DependsOn("pivot_airstrip_table"),
                "filename": "airstrip_arrivals_and_departure",
            }
            | (params_dict.get("persist_airstrip_summary") or {}),
            method="call",
        ),
        "filter_am_events": Node(
            async_task=filter_df.validate()
            .set_task_instance_id("filter_am_events")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "column_name": "event_type",
                "op": "equal",
                "value": "airstrip_maintenance",
                "df": DependsOn("events_temporal"),
                "reset_index": False,
            }
            | (params_dict.get("filter_am_events") or {}),
            method="call",
        ),
        "normalize_am_values": Node(
            async_task=normalize_json_column.validate()
            .set_task_instance_id("normalize_am_values")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "column": "event_details",
                "df": DependsOn("filter_am_events"),
                "skip_if_not_exists": True,
                "sort_columns": True,
            }
            | (params_dict.get("normalize_am_values") or {}),
            method="call",
        ),
        "rename_am": Node(
            async_task=transform_columns.validate()
            .set_task_instance_id("rename_am")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "rename_columns": {
                    "event_details__maintenance_type": "activity",
                },
                "skip_missing_rename": True,
                "required_columns": [
                    "event_details__maintenance_type",
                ],
                "df": DependsOn("normalize_am_values"),
            }
            | (params_dict.get("rename_am") or {}),
            method="call",
        ),
        "filter_cols": Node(
            async_task=filter_columns.validate()
            .set_task_instance_id("filter_cols")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("rename_am"),
                "columns": [
                    "date",
                    "activity",
                ],
            }
            | (params_dict.get("filter_cols") or {}),
            method="call",
        ),
        "capitalize_activity_col": Node(
            async_task=capitalize_text.validate()
            .set_task_instance_id("capitalize_activity_col")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("filter_cols"),
                "column": "activity",
            }
            | (params_dict.get("capitalize_activity_col") or {}),
            method="call",
        ),
        "persist_air_maintenance": Node(
            async_task=persist_df.validate()
            .set_task_instance_id("persist_air_maintenance")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "filetype": "csv",
                "df": DependsOn("capitalize_activity_col"),
                "filename": "airstrip_maintenance_table",
            }
            | (params_dict.get("persist_air_maintenance") or {}),
            method="call",
        ),
        "mnc_events_dashboard": Node(
            async_task=gather_dashboard.validate()
            .set_task_instance_id("mnc_events_dashboard")
            .handle_errors()
            .with_tracing()
            .set_executor("lithops"),
            partial={
                "details": DependsOn("workflow_details"),
                "time_range": DependsOn("time_range"),
                "groupers": DependsOn("groupers"),
            }
            | (params_dict.get("mnc_events_dashboard") or {}),
            method="call",
        ),
    }
    graph = Graph(dependencies=dependencies, nodes=nodes)
    results = graph.execute()
    return results
