# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details

# ruff: noqa: E402

"""WARNING: This file is generated in a testing context and should not be used in production.
Lines specific to the testing context are marked with a test tube emoji (🧪) to indicate
that they would not be included (or would be different) in the production version of this file.
"""

import json
import os
import warnings  # 🧪

from ecoscope_workflows_core.tasks.config import (
    set_workflow_details as set_workflow_details,
)
from ecoscope_workflows_core.tasks.filter import set_time_range as set_time_range
from ecoscope_workflows_core.tasks.groupby import set_groupers as set_groupers
from ecoscope_workflows_core.tasks.io import set_er_connection as set_er_connection
from ecoscope_workflows_core.testing import create_task_magicmock  # 🧪

get_events = create_task_magicmock(  # 🧪
    anchor="ecoscope_workflows_ext_ecoscope.tasks.io",  # 🧪
    func_name="get_events",  # 🧪
)  # 🧪
from ecoscope_workflows_core.tasks.results import gather_dashboard as gather_dashboard
from ecoscope_workflows_core.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope_workflows_core.tasks.skip import any_is_empty_df as any_is_empty_df
from ecoscope_workflows_core.tasks.transformation import (
    add_temporal_index as add_temporal_index,
)
from ecoscope_workflows_core.tasks.transformation import (
    extract_column_as_type as extract_column_as_type,
)
from ecoscope_workflows_core.tasks.transformation import filter_df as filter_df
from ecoscope_workflows_core.tasks.transformation import map_columns as map_columns
from ecoscope_workflows_ext_ecoscope.tasks.analysis import summarize_df as summarize_df
from ecoscope_workflows_ext_ecoscope.tasks.io import persist_df as persist_df
from ecoscope_workflows_ext_ecoscope.tasks.transformation import (
    normalize_json_column as normalize_json_column,
)
from ecoscope_workflows_ext_mnc.tasks import capitalize_text as capitalize_text
from ecoscope_workflows_ext_mnc.tasks import convert_to_int as convert_to_int
from ecoscope_workflows_ext_mnc.tasks import filter_columns as filter_columns
from ecoscope_workflows_ext_mnc.tasks import pivot_df as pivot_df
from ecoscope_workflows_ext_mnc.tasks import (
    remove_brackets_from_column as remove_brackets_from_column,
)
from ecoscope_workflows_ext_mnc.tasks import (
    replace_missing_with_label as replace_missing_with_label,
)
from ecoscope_workflows_ext_mnc.tasks import transform_columns as transform_columns

from ..params import Params


def main(params: Params):
    warnings.warn("This test script should not be used in production!")  # 🧪

    params_dict = json.loads(params.model_dump_json(exclude_unset=True))

    workflow_details = (
        set_workflow_details.validate()
        .set_task_instance_id("workflow_details")
        .handle_errors()
        .with_tracing()
        .partial(**(params_dict.get("workflow_details") or {}))
        .call()
    )

    time_range = (
        set_time_range.validate()
        .set_task_instance_id("time_range")
        .handle_errors()
        .with_tracing()
        .partial(**(params_dict.get("time_range") or {}))
        .call()
    )

    groupers = (
        set_groupers.validate()
        .set_task_instance_id("groupers")
        .handle_errors()
        .with_tracing()
        .partial(groupers=[], **(params_dict.get("groupers") or {}))
        .call()
    )

    er_client_name = (
        set_er_connection.validate()
        .set_task_instance_id("er_client_name")
        .handle_errors()
        .with_tracing()
        .partial(**(params_dict.get("er_client_name") or {}))
        .call()
    )

    get_events_data = (
        get_events.validate()
        .set_task_instance_id("get_events_data")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            client=er_client_name,
            time_range=time_range,
            event_columns=[
                "id",
                "time",
                "event_type",
                "event_category",
                "reported_by",
                "serial_number",
                "geometry",
                "created_at",
                "event_details",
                "patrols",
            ],
            event_types=[],
            raise_on_empty=True,
            include_details=True,
            include_updates=False,
            include_related_events=False,
            include_null_geometry=False,
            include_display_values=False,
            **(params_dict.get("get_events_data") or {}),
        )
        .call()
    )

    extract_event_date = (
        extract_column_as_type.validate()
        .set_task_instance_id("extract_event_date")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=get_events_data,
            column_name="time",
            output_type="date",
            output_column_name="date",
            **(params_dict.get("extract_event_date") or {}),
        )
        .call()
    )

    events_temporal = (
        add_temporal_index.validate()
        .set_task_instance_id("events_temporal")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=extract_event_date,
            time_col="date",
            groupers=groupers,
            cast_to_datetime=True,
            format="mixed",
            **(params_dict.get("events_temporal") or {}),
        )
        .call()
    )

    filter_balloon_events = (
        filter_df.validate()
        .set_task_instance_id("filter_balloon_events")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            column_name="event_type",
            op="equal",
            value="balloon_landing",
            df=events_temporal,
            reset_index=False,
            **(params_dict.get("filter_balloon_events") or {}),
        )
        .call()
    )

    normalize_balloon_values = (
        normalize_json_column.validate()
        .set_task_instance_id("normalize_balloon_values")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            column="event_details",
            df=filter_balloon_events,
            skip_if_not_exists=True,
            sort_columns=True,
            **(params_dict.get("normalize_balloon_values") or {}),
        )
        .call()
    )

    rename_balloon_boma = (
        transform_columns.validate()
        .set_task_instance_id("rename_balloon_boma")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            drop_columns=[],
            retain_columns=[],
            rename_columns={
                "event_details__of_passengers": "no_of_passengers",
                "event_details__balloon_company": "balloon_company",
                "event_details__where_are_clients_staying": "lodge",
            },
            skip_missing_rename=True,
            required_columns=[
                "event_details__of_passengers",
                "event_details__balloon_company",
                "date",
                "event_details__where_are_clients_staying",
            ],
            df=normalize_balloon_values,
            **(params_dict.get("rename_balloon_boma") or {}),
        )
        .call()
    )

    remove_balloon_brackets = (
        remove_brackets_from_column.validate()
        .set_task_instance_id("remove_balloon_brackets")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=rename_balloon_boma,
            columns=["lodge", "balloon_company"],
            **(params_dict.get("remove_balloon_brackets") or {}),
        )
        .call()
    )

    replace_lodge_nulls = (
        replace_missing_with_label.validate()
        .set_task_instance_id("replace_lodge_nulls")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=remove_balloon_brackets,
            columns=["lodge"],
            label="other",
            **(params_dict.get("replace_lodge_nulls") or {}),
        )
        .call()
    )

    convert_passengers_int = (
        convert_to_int.validate()
        .set_task_instance_id("convert_passengers_int")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=replace_lodge_nulls,
            columns=["no_of_passengers"],
            errors="coerce",
            fill_value=0,
            inplace=False,
            **(params_dict.get("convert_passengers_int") or {}),
        )
        .call()
    )

    generate_balloon_table = (
        summarize_df.validate()
        .set_task_instance_id("generate_balloon_table")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            groupby_cols=["date", "balloon_company", "lodge"],
            summary_params=[
                {
                    "display_name": "no_of_passengers",
                    "aggregator": "sum",
                    "column": "no_of_passengers",
                }
            ],
            reset_index=True,
            df=convert_passengers_int,
            **(params_dict.get("generate_balloon_table") or {}),
        )
        .call()
    )

    capitalize_balloon_co = (
        capitalize_text.validate()
        .set_task_instance_id("capitalize_balloon_co")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=generate_balloon_table,
            column="balloon_company",
            **(params_dict.get("capitalize_balloon_co") or {}),
        )
        .call()
    )

    capitalize_lodge = (
        capitalize_text.validate()
        .set_task_instance_id("capitalize_lodge")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=capitalize_balloon_co,
            column="lodge",
            **(params_dict.get("capitalize_lodge") or {}),
        )
        .call()
    )

    persist_balloon_summary = (
        persist_df.validate()
        .set_task_instance_id("persist_balloon_summary")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filetype="csv",
            df=capitalize_lodge,
            filename="balloon_landing_by_date",
            **(params_dict.get("persist_balloon_summary") or {}),
        )
        .call()
    )

    filter_airstrip_events = (
        filter_df.validate()
        .set_task_instance_id("filter_airstrip_events")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            column_name="event_type",
            op="equal",
            value="airstrip_operations",
            df=events_temporal,
            reset_index=False,
            **(params_dict.get("filter_airstrip_events") or {}),
        )
        .call()
    )

    normalize_airstrip_values = (
        normalize_json_column.validate()
        .set_task_instance_id("normalize_airstrip_values")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            column="event_details",
            df=filter_airstrip_events,
            skip_if_not_exists=True,
            sort_columns=True,
            **(params_dict.get("normalize_airstrip_values") or {}),
        )
        .call()
    )

    rename_airstrip = (
        map_columns.validate()
        .set_task_instance_id("rename_airstrip")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            raise_if_not_found=True,
            drop_columns=[],
            retain_columns=[],
            rename_columns={
                "event_details__guide": "guide",
                "event_details__airline": "airline",
                "event_details__attendant": "attendant",
                "event_details__camplodge": "camp_lodge",
                "event_details__flight_number": "flight_number",
                "event_details__number_of_clients": "number_of_clients",
                "event_details__arrival_or_departure": "arrival_or_departure",
            },
            df=normalize_airstrip_values,
            **(params_dict.get("rename_airstrip") or {}),
        )
        .call()
    )

    remove_air_brackets = (
        remove_brackets_from_column.validate()
        .set_task_instance_id("remove_air_brackets")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=rename_airstrip,
            columns=["airline", "attendant", "camp_lodge", "arrival_or_departure"],
            **(params_dict.get("remove_air_brackets") or {}),
        )
        .call()
    )

    replace_camp_lodge_nulls = (
        replace_missing_with_label.validate()
        .set_task_instance_id("replace_camp_lodge_nulls")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=remove_air_brackets,
            columns=["camp_lodge"],
            label="other",
            **(params_dict.get("replace_camp_lodge_nulls") or {}),
        )
        .call()
    )

    convert_clients_int = (
        convert_to_int.validate()
        .set_task_instance_id("convert_clients_int")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=replace_camp_lodge_nulls,
            columns=["number_of_clients"],
            errors="coerce",
            fill_value=0,
            inplace=False,
            **(params_dict.get("convert_clients_int") or {}),
        )
        .call()
    )

    lodge_scase = (
        capitalize_text.validate()
        .set_task_instance_id("lodge_scase")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=convert_clients_int,
            column="camp_lodge",
            **(params_dict.get("lodge_scase") or {}),
        )
        .call()
    )

    airstrip_summary_table = (
        summarize_df.validate()
        .set_task_instance_id("airstrip_summary_table")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=lodge_scase,
            groupby_cols=["camp_lodge", "arrival_or_departure"],
            summary_params=[
                {
                    "display_name": "no_of_passengers",
                    "aggregator": "sum",
                    "column": "number_of_clients",
                    "decimal_places": 0,
                }
            ],
            reset_index=True,
            **(params_dict.get("airstrip_summary_table") or {}),
        )
        .call()
    )

    pivot_airstrip_table = (
        pivot_df.validate()
        .set_task_instance_id("pivot_airstrip_table")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=airstrip_summary_table,
            index_col="camp_lodge",
            columns_col="arrival_or_departure",
            values_col="no_of_passengers",
            reset_idx=True,
            **(params_dict.get("pivot_airstrip_table") or {}),
        )
        .call()
    )

    persist_airstrip_summary = (
        persist_df.validate()
        .set_task_instance_id("persist_airstrip_summary")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filetype="csv",
            df=pivot_airstrip_table,
            filename="airstrip_arrivals_and_departure",
            **(params_dict.get("persist_airstrip_summary") or {}),
        )
        .call()
    )

    filter_am_events = (
        filter_df.validate()
        .set_task_instance_id("filter_am_events")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            column_name="event_type",
            op="equal",
            value="airstrip_maintenance",
            df=events_temporal,
            reset_index=False,
            **(params_dict.get("filter_am_events") or {}),
        )
        .call()
    )

    normalize_am_values = (
        normalize_json_column.validate()
        .set_task_instance_id("normalize_am_values")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            column="event_details",
            df=filter_am_events,
            skip_if_not_exists=True,
            sort_columns=True,
            **(params_dict.get("normalize_am_values") or {}),
        )
        .call()
    )

    rename_am = (
        transform_columns.validate()
        .set_task_instance_id("rename_am")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            drop_columns=[],
            retain_columns=[],
            rename_columns={"event_details__maintenance_type": "activity"},
            skip_missing_rename=True,
            required_columns=["event_details__maintenance_type"],
            df=normalize_am_values,
            **(params_dict.get("rename_am") or {}),
        )
        .call()
    )

    filter_cols = (
        filter_columns.validate()
        .set_task_instance_id("filter_cols")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=rename_am,
            columns=["date", "activity"],
            exclude=[],
            **(params_dict.get("filter_cols") or {}),
        )
        .call()
    )

    capitalize_activity_col = (
        capitalize_text.validate()
        .set_task_instance_id("capitalize_activity_col")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=filter_cols,
            column="activity",
            **(params_dict.get("capitalize_activity_col") or {}),
        )
        .call()
    )

    persist_air_maintenance = (
        persist_df.validate()
        .set_task_instance_id("persist_air_maintenance")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filetype="csv",
            df=capitalize_activity_col,
            filename="airstrip_maintenance_table",
            **(params_dict.get("persist_air_maintenance") or {}),
        )
        .call()
    )

    mnc_events_dashboard = (
        gather_dashboard.validate()
        .set_task_instance_id("mnc_events_dashboard")
        .handle_errors()
        .with_tracing()
        .partial(
            details=workflow_details,
            widgets=[],
            time_range=time_range,
            groupers=groupers,
            **(params_dict.get("mnc_events_dashboard") or {}),
        )
        .call()
    )

    return mnc_events_dashboard
