# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details

# ruff: noqa: E402

"""WARNING: This file is generated in a testing context and should not be used in production.
Lines specific to the testing context are marked with a test tube emoji (🧪) to indicate
that they would not be included (or would be different) in the production version of this file.
"""

import json
import os
import warnings  # 🧪

from ecoscope_workflows_core.tasks.config import (
    set_workflow_details as set_workflow_details,
)
from ecoscope_workflows_core.tasks.filter import set_time_range as set_time_range
from ecoscope_workflows_core.tasks.groupby import set_groupers as set_groupers
from ecoscope_workflows_core.tasks.io import set_er_connection as set_er_connection
from ecoscope_workflows_core.testing import create_task_magicmock  # 🧪

get_events = create_task_magicmock(  # 🧪
    anchor="ecoscope_workflows_ext_ecoscope.tasks.io",  # 🧪
    func_name="get_events",  # 🧪
)  # 🧪
from ecoscope_workflows_core.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope_workflows_core.tasks.skip import any_is_empty_df as any_is_empty_df
from ecoscope_workflows_core.tasks.transformation import (
    add_temporal_index as add_temporal_index,
)
from ecoscope_workflows_core.tasks.transformation import (
    extract_column_as_type as extract_column_as_type,
)
from ecoscope_workflows_core.tasks.transformation import filter_df as filter_df

process_events_details = create_task_magicmock(  # 🧪
    anchor="ecoscope_workflows_ext_custom.tasks.io",  # 🧪
    func_name="process_events_details",  # 🧪
)  # 🧪
from ecoscope_workflows_ext_custom.tasks.transformation import (
    drop_column_prefix as drop_column_prefix,
)
from ecoscope_workflows_ext_ecoscope.tasks.transformation import (
    normalize_json_column as normalize_json_column,
)

process_events_details = create_task_magicmock(  # 🧪
    anchor="ecoscope_workflows_ext_custom.tasks.io",  # 🧪
    func_name="process_events_details",  # 🧪
)  # 🧪

process_events_details = create_task_magicmock(  # 🧪
    anchor="ecoscope_workflows_ext_custom.tasks.io",  # 🧪
    func_name="process_events_details",  # 🧪
)  # 🧪

process_events_details = create_task_magicmock(  # 🧪
    anchor="ecoscope_workflows_ext_custom.tasks.io",  # 🧪
    func_name="process_events_details",  # 🧪
)  # 🧪
from ecoscope_workflows_core.tasks.results import gather_dashboard as gather_dashboard
from ecoscope_workflows_core.tasks.transformation import map_columns as map_columns
from ecoscope_workflows_ext_ecoscope.tasks.analysis import summarize_df as summarize_df
from ecoscope_workflows_ext_ecoscope.tasks.io import persist_df as persist_df
from ecoscope_workflows_ext_mnc.tasks import capitalize_text as capitalize_text
from ecoscope_workflows_ext_mnc.tasks import convert_to_int as convert_to_int
from ecoscope_workflows_ext_mnc.tasks import pivot_df as pivot_df
from ecoscope_workflows_ext_mnc.tasks import (
    remove_brackets_from_column as remove_brackets_from_column,
)
from ecoscope_workflows_ext_mnc.tasks import (
    replace_missing_with_label as replace_missing_with_label,
)

from ..params import Params


def main(params: Params):
    warnings.warn("This test script should not be used in production!")  # 🧪

    params_dict = json.loads(params.model_dump_json(exclude_unset=True))

    workflow_details = (
        set_workflow_details.validate()
        .set_task_instance_id("workflow_details")
        .handle_errors()
        .with_tracing()
        .partial(**(params_dict.get("workflow_details") or {}))
        .call()
    )

    time_range = (
        set_time_range.validate()
        .set_task_instance_id("time_range")
        .handle_errors()
        .with_tracing()
        .partial(**(params_dict.get("time_range") or {}))
        .call()
    )

    groupers = (
        set_groupers.validate()
        .set_task_instance_id("groupers")
        .handle_errors()
        .with_tracing()
        .partial(groupers=[], **(params_dict.get("groupers") or {}))
        .call()
    )

    er_client_name = (
        set_er_connection.validate()
        .set_task_instance_id("er_client_name")
        .handle_errors()
        .with_tracing()
        .partial(**(params_dict.get("er_client_name") or {}))
        .call()
    )

    get_events_data = (
        get_events.validate()
        .set_task_instance_id("get_events_data")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            client=er_client_name,
            time_range=time_range,
            event_columns=[
                "id",
                "time",
                "event_type",
                "event_category",
                "reported_by",
                "serial_number",
                "geometry",
                "created_at",
                "event_details",
                "patrols",
            ],
            event_types=[
                "balloon_landing",
                "airstrip_operations",
                "airstrip_maintenance",
                "airline_complaint",
            ],
            raise_on_empty=True,
            include_details=True,
            include_updates=False,
            include_related_events=False,
            include_null_geometry=False,
            include_display_values=False,
            **(params_dict.get("get_events_data") or {}),
        )
        .call()
    )

    extract_event_date = (
        extract_column_as_type.validate()
        .set_task_instance_id("extract_event_date")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=get_events_data,
            column_name="time",
            output_type="date",
            output_column_name="date",
            **(params_dict.get("extract_event_date") or {}),
        )
        .call()
    )

    events_temporal = (
        add_temporal_index.validate()
        .set_task_instance_id("events_temporal")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=extract_event_date,
            time_col="date",
            groupers=groupers,
            cast_to_datetime=True,
            format="mixed",
            **(params_dict.get("events_temporal") or {}),
        )
        .call()
    )

    filter_balloon_events = (
        filter_df.validate()
        .set_task_instance_id("filter_balloon_events")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            column_name="event_type",
            op="equal",
            value="balloon_landing",
            df=events_temporal,
            reset_index=False,
            **(params_dict.get("filter_balloon_events") or {}),
        )
        .call()
    )

    filter_airstrip_operations = (
        filter_df.validate()
        .set_task_instance_id("filter_airstrip_operations")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            column_name="event_type",
            op="equal",
            value="airstrip_operations",
            df=events_temporal,
            reset_index=False,
            **(params_dict.get("filter_airstrip_operations") or {}),
        )
        .call()
    )

    filter_airstrip_maintenance = (
        filter_df.validate()
        .set_task_instance_id("filter_airstrip_maintenance")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            column_name="event_type",
            op="equal",
            value="airstrip_maintenance",
            df=events_temporal,
            reset_index=False,
            **(params_dict.get("filter_airstrip_maintenance") or {}),
        )
        .call()
    )

    filter_airline_complaints = (
        filter_df.validate()
        .set_task_instance_id("filter_airline_complaints")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            column_name="event_type",
            op="equal",
            value="airline_complaint",
            df=events_temporal,
            reset_index=False,
            **(params_dict.get("filter_airline_complaints") or {}),
        )
        .call()
    )

    process_balloon_details = (
        process_events_details.validate()
        .set_task_instance_id("process_balloon_details")
        .handle_errors()
        .with_tracing()
        .partial(
            df=filter_balloon_events,
            client=er_client_name,
            map_to_titles=True,
            ordered=True,
            **(params_dict.get("process_balloon_details") or {}),
        )
        .call()
    )

    normalize_balloon_values = (
        normalize_json_column.validate()
        .set_task_instance_id("normalize_balloon_values")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            column="event_details",
            df=process_balloon_details,
            skip_if_not_exists=True,
            sort_columns=True,
            **(params_dict.get("normalize_balloon_values") or {}),
        )
        .call()
    )

    drop_balloon_prefix = (
        drop_column_prefix.validate()
        .set_task_instance_id("drop_balloon_prefix")
        .handle_errors()
        .with_tracing()
        .partial(
            df=normalize_balloon_values,
            prefix="event_details__",
            duplicate_strategy="keep_original",
            **(params_dict.get("drop_balloon_prefix") or {}),
        )
        .call()
    )

    process_airstrip_details = (
        process_events_details.validate()
        .set_task_instance_id("process_airstrip_details")
        .handle_errors()
        .with_tracing()
        .partial(
            df=filter_airstrip_operations,
            client=er_client_name,
            map_to_titles=True,
            ordered=True,
            **(params_dict.get("process_airstrip_details") or {}),
        )
        .call()
    )

    normalize_airstrip_op_values = (
        normalize_json_column.validate()
        .set_task_instance_id("normalize_airstrip_op_values")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            column="event_details",
            df=process_airstrip_details,
            skip_if_not_exists=True,
            sort_columns=True,
            **(params_dict.get("normalize_airstrip_op_values") or {}),
        )
        .call()
    )

    drop_airstrip_op_prefix = (
        drop_column_prefix.validate()
        .set_task_instance_id("drop_airstrip_op_prefix")
        .handle_errors()
        .with_tracing()
        .partial(
            df=normalize_airstrip_op_values,
            prefix="event_details__",
            duplicate_strategy="keep_original",
            **(params_dict.get("drop_airstrip_op_prefix") or {}),
        )
        .call()
    )

    process_airstrip_maint_details = (
        process_events_details.validate()
        .set_task_instance_id("process_airstrip_maint_details")
        .handle_errors()
        .with_tracing()
        .partial(
            df=filter_airstrip_maintenance,
            client=er_client_name,
            map_to_titles=True,
            ordered=True,
            **(params_dict.get("process_airstrip_maint_details") or {}),
        )
        .call()
    )

    normalize_airstrip_maint_vals = (
        normalize_json_column.validate()
        .set_task_instance_id("normalize_airstrip_maint_vals")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            column="event_details",
            df=process_airstrip_maint_details,
            skip_if_not_exists=True,
            sort_columns=True,
            **(params_dict.get("normalize_airstrip_maint_vals") or {}),
        )
        .call()
    )

    drop_airstrip_maintenance_prefix = (
        drop_column_prefix.validate()
        .set_task_instance_id("drop_airstrip_maintenance_prefix")
        .handle_errors()
        .with_tracing()
        .partial(
            df=normalize_airstrip_maint_vals,
            prefix="event_details__",
            duplicate_strategy="keep_original",
            **(params_dict.get("drop_airstrip_maintenance_prefix") or {}),
        )
        .call()
    )

    process_airline_comp_details = (
        process_events_details.validate()
        .set_task_instance_id("process_airline_comp_details")
        .handle_errors()
        .with_tracing()
        .partial(
            df=filter_airline_complaints,
            client=er_client_name,
            map_to_titles=True,
            ordered=True,
            **(params_dict.get("process_airline_comp_details") or {}),
        )
        .call()
    )

    normalize_airline_comp_vals = (
        normalize_json_column.validate()
        .set_task_instance_id("normalize_airline_comp_vals")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            column="event_details",
            df=process_airline_comp_details,
            skip_if_not_exists=True,
            sort_columns=True,
            **(params_dict.get("normalize_airline_comp_vals") or {}),
        )
        .call()
    )

    drop_airline_complaint_prefix = (
        drop_column_prefix.validate()
        .set_task_instance_id("drop_airline_complaint_prefix")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=normalize_airline_comp_vals,
            prefix="event_details__",
            duplicate_strategy="keep_original",
            **(params_dict.get("drop_airline_complaint_prefix") or {}),
        )
        .call()
    )

    map_balloon_columns = (
        map_columns.validate()
        .set_task_instance_id("map_balloon_columns")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=drop_balloon_prefix,
            drop_columns=[],
            retain_columns=[
                "date",
                "Balloon Company",
                "Where are clients staying?",
                "# of passengers",
            ],
            rename_columns={
                "Balloon Company": "balloon_company",
                "Where are clients staying?": "where_are_clients_staying",
                "# of passengers": "no_of_passengers",
            },
            raise_if_not_found=False,
            **(params_dict.get("map_balloon_columns") or {}),
        )
        .call()
    )

    remove_balloon_brackets = (
        remove_brackets_from_column.validate()
        .set_task_instance_id("remove_balloon_brackets")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=map_balloon_columns,
            columns=["balloon_company", "where_are_clients_staying"],
            **(params_dict.get("remove_balloon_brackets") or {}),
        )
        .call()
    )

    persist_balloon_landing = (
        persist_df.validate()
        .set_task_instance_id("persist_balloon_landing")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filetype="csv",
            df=remove_balloon_brackets,
            filename="balloon_landing_summary_table",
            **(params_dict.get("persist_balloon_landing") or {}),
        )
        .call()
    )

    map_airstrip_op_columns = (
        map_columns.validate()
        .set_task_instance_id("map_airstrip_op_columns")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=drop_airstrip_op_prefix,
            drop_columns=[],
            retain_columns=[],
            rename_columns={
                "Airline": "airline",
                "Arrival or departure": "arrival_departure",
                "Attendant": "attendant",
                "Camp/Lodge": "camp_lodge",
                "Number of clients": "no_of_clients",
            },
            raise_if_not_found=False,
            **(params_dict.get("map_airstrip_op_columns") or {}),
        )
        .call()
    )

    remove_airstrip_op_brackets = (
        remove_brackets_from_column.validate()
        .set_task_instance_id("remove_airstrip_op_brackets")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=map_airstrip_op_columns,
            columns=["airline", "arrival_departure", "attendant", "camp_lodge"],
            **(params_dict.get("remove_airstrip_op_brackets") or {}),
        )
        .call()
    )

    replace_airstrip_op_nulls = (
        replace_missing_with_label.validate()
        .set_task_instance_id("replace_airstrip_op_nulls")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=remove_airstrip_op_brackets,
            columns=["camp_lodge"],
            label="other",
            **(params_dict.get("replace_airstrip_op_nulls") or {}),
        )
        .call()
    )

    convert_airstrip_op_ints = (
        convert_to_int.validate()
        .set_task_instance_id("convert_airstrip_op_ints")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=replace_airstrip_op_nulls,
            columns=["no_of_clients"],
            errors="coerce",
            fill_value=0,
            inplace=False,
            **(params_dict.get("convert_airstrip_op_ints") or {}),
        )
        .call()
    )

    capitalize_camp_lodge = (
        capitalize_text.validate()
        .set_task_instance_id("capitalize_camp_lodge")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=convert_airstrip_op_ints,
            column="camp_lodge",
            **(params_dict.get("capitalize_camp_lodge") or {}),
        )
        .call()
    )

    airstrip_op_summary_table = (
        summarize_df.validate()
        .set_task_instance_id("airstrip_op_summary_table")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=capitalize_camp_lodge,
            groupby_cols=["camp_lodge", "arrival_departure"],
            summary_params=[
                {
                    "display_name": "no_of_clients",
                    "aggregator": "sum",
                    "column": "no_of_clients",
                    "decimal_places": 0,
                }
            ],
            reset_index=True,
            **(params_dict.get("airstrip_op_summary_table") or {}),
        )
        .call()
    )

    pivot_airstrip_ops = (
        pivot_df.validate()
        .set_task_instance_id("pivot_airstrip_ops")
        .handle_errors()
        .with_tracing()
        .partial(
            df=airstrip_op_summary_table,
            index_col="camp_lodge",
            columns_col="arrival_departure",
            values_col="no_of_clients",
            reset_idx=True,
            **(params_dict.get("pivot_airstrip_ops") or {}),
        )
        .call()
    )

    convert_pivot_int = (
        convert_to_int.validate()
        .set_task_instance_id("convert_pivot_int")
        .handle_errors()
        .with_tracing()
        .partial(
            df=pivot_airstrip_ops,
            columns=["arrival", "departure"],
            errors="coerce",
            fill_value=0,
            inplace=False,
            **(params_dict.get("convert_pivot_int") or {}),
        )
        .call()
    )

    persist_airstrip_operations = (
        persist_df.validate()
        .set_task_instance_id("persist_airstrip_operations")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filetype="csv",
            df=convert_pivot_int,
            filename="airstrip_operations_summary_table",
            **(params_dict.get("persist_airstrip_operations") or {}),
        )
        .call()
    )

    map_airstrip_maintenance = (
        map_columns.validate()
        .set_task_instance_id("map_airstrip_maintenance")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=drop_airstrip_maintenance_prefix,
            drop_columns=[],
            retain_columns=["date", "Maintenance type"],
            rename_columns={"Maintenance type": "maintenance_type"},
            raise_if_not_found=False,
            **(params_dict.get("map_airstrip_maintenance") or {}),
        )
        .call()
    )

    persist_airstrip_maintenance = (
        persist_df.validate()
        .set_task_instance_id("persist_airstrip_maintenance")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filetype="csv",
            df=map_airstrip_maintenance,
            filename="airstrip_maintenance_summary_table",
            **(params_dict.get("persist_airstrip_maintenance") or {}),
        )
        .call()
    )

    mnc_events_dashboard = (
        gather_dashboard.validate()
        .set_task_instance_id("mnc_events_dashboard")
        .handle_errors()
        .with_tracing()
        .partial(
            details=workflow_details,
            widgets=[],
            time_range=time_range,
            groupers=groupers,
            **(params_dict.get("mnc_events_dashboard") or {}),
        )
        .call()
    )

    return mnc_events_dashboard
