# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details

# ruff: noqa: E402

"""WARNING: This file is generated in a testing context and should not be used in production.
Lines specific to the testing context are marked with a test tube emoji (🧪) to indicate
that they would not be included (or would be different) in the production version of this file.
"""

import json
import os
import warnings  # 🧪

from ecoscope_workflows_core.graph import DependsOn, Graph, Node
from ecoscope_workflows_core.tasks.config import (
    set_workflow_details as set_workflow_details,
)
from ecoscope_workflows_core.tasks.filter import set_time_range as set_time_range
from ecoscope_workflows_core.tasks.groupby import set_groupers as set_groupers
from ecoscope_workflows_core.tasks.io import set_er_connection as set_er_connection
from ecoscope_workflows_core.testing import create_task_magicmock  # 🧪

get_events = create_task_magicmock(  # 🧪
    anchor="ecoscope_workflows_ext_ecoscope.tasks.io",  # 🧪
    func_name="get_events",  # 🧪
)  # 🧪
from ecoscope_workflows_core.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope_workflows_core.tasks.skip import any_is_empty_df as any_is_empty_df
from ecoscope_workflows_core.tasks.transformation import (
    add_temporal_index as add_temporal_index,
)
from ecoscope_workflows_core.tasks.transformation import (
    extract_column_as_type as extract_column_as_type,
)
from ecoscope_workflows_core.tasks.transformation import filter_df as filter_df

process_events_details = create_task_magicmock(  # 🧪
    anchor="ecoscope_workflows_ext_custom.tasks.io",  # 🧪
    func_name="process_events_details",  # 🧪
)  # 🧪
from ecoscope_workflows_ext_custom.tasks.transformation import (
    drop_column_prefix as drop_column_prefix,
)
from ecoscope_workflows_ext_ecoscope.tasks.transformation import (
    normalize_json_column as normalize_json_column,
)

process_events_details = create_task_magicmock(  # 🧪
    anchor="ecoscope_workflows_ext_custom.tasks.io",  # 🧪
    func_name="process_events_details",  # 🧪
)  # 🧪

process_events_details = create_task_magicmock(  # 🧪
    anchor="ecoscope_workflows_ext_custom.tasks.io",  # 🧪
    func_name="process_events_details",  # 🧪
)  # 🧪

process_events_details = create_task_magicmock(  # 🧪
    anchor="ecoscope_workflows_ext_custom.tasks.io",  # 🧪
    func_name="process_events_details",  # 🧪
)  # 🧪
from ecoscope_workflows_core.tasks.results import gather_dashboard as gather_dashboard
from ecoscope_workflows_core.tasks.transformation import map_columns as map_columns
from ecoscope_workflows_ext_ecoscope.tasks.analysis import summarize_df as summarize_df
from ecoscope_workflows_ext_ecoscope.tasks.io import persist_df as persist_df
from ecoscope_workflows_ext_mnc.tasks import capitalize_text as capitalize_text
from ecoscope_workflows_ext_mnc.tasks import convert_to_int as convert_to_int
from ecoscope_workflows_ext_mnc.tasks import pivot_df as pivot_df
from ecoscope_workflows_ext_mnc.tasks import (
    remove_brackets_from_column as remove_brackets_from_column,
)
from ecoscope_workflows_ext_mnc.tasks import (
    replace_missing_with_label as replace_missing_with_label,
)

from ..params import Params


def main(params: Params):
    warnings.warn("This test script should not be used in production!")  # 🧪

    params_dict = json.loads(params.model_dump_json(exclude_unset=True))

    dependencies = {
        "workflow_details": [],
        "time_range": [],
        "groupers": [],
        "er_client_name": [],
        "get_events_data": ["er_client_name", "time_range"],
        "extract_event_date": ["get_events_data"],
        "events_temporal": ["extract_event_date", "groupers"],
        "filter_balloon_events": ["events_temporal"],
        "filter_airstrip_operations": ["events_temporal"],
        "filter_airstrip_maintenance": ["events_temporal"],
        "filter_airline_complaints": ["events_temporal"],
        "process_balloon_details": ["filter_balloon_events", "er_client_name"],
        "normalize_balloon_values": ["process_balloon_details"],
        "drop_balloon_prefix": ["normalize_balloon_values"],
        "process_airstrip_details": ["filter_airstrip_operations", "er_client_name"],
        "normalize_airstrip_op_values": ["process_airstrip_details"],
        "drop_airstrip_op_prefix": ["normalize_airstrip_op_values"],
        "process_airstrip_maint_details": [
            "filter_airstrip_maintenance",
            "er_client_name",
        ],
        "normalize_airstrip_maint_vals": ["process_airstrip_maint_details"],
        "drop_airstrip_maintenance_prefix": ["normalize_airstrip_maint_vals"],
        "process_airline_comp_details": ["filter_airline_complaints", "er_client_name"],
        "normalize_airline_comp_vals": ["process_airline_comp_details"],
        "drop_airline_complaint_prefix": ["normalize_airline_comp_vals"],
        "map_balloon_columns": ["drop_balloon_prefix"],
        "remove_balloon_brackets": ["map_balloon_columns"],
        "persist_balloon_landing": ["remove_balloon_brackets"],
        "map_airstrip_op_columns": ["drop_airstrip_op_prefix"],
        "remove_airstrip_op_brackets": ["map_airstrip_op_columns"],
        "replace_airstrip_op_nulls": ["remove_airstrip_op_brackets"],
        "convert_airstrip_op_ints": ["replace_airstrip_op_nulls"],
        "capitalize_camp_lodge": ["convert_airstrip_op_ints"],
        "airstrip_op_summary_table": ["capitalize_camp_lodge"],
        "pivot_airstrip_ops": ["airstrip_op_summary_table"],
        "convert_pivot_int": ["pivot_airstrip_ops"],
        "persist_airstrip_operations": ["convert_pivot_int"],
        "map_airstrip_maintenance": ["drop_airstrip_maintenance_prefix"],
        "persist_airstrip_maintenance": ["map_airstrip_maintenance"],
        "mnc_events_dashboard": ["workflow_details", "time_range", "groupers"],
    }

    nodes = {
        "workflow_details": Node(
            async_task=set_workflow_details.validate()
            .set_task_instance_id("workflow_details")
            .handle_errors()
            .with_tracing()
            .set_executor("lithops"),
            partial=(params_dict.get("workflow_details") or {}),
            method="call",
        ),
        "time_range": Node(
            async_task=set_time_range.validate()
            .set_task_instance_id("time_range")
            .handle_errors()
            .with_tracing()
            .set_executor("lithops"),
            partial=(params_dict.get("time_range") or {}),
            method="call",
        ),
        "groupers": Node(
            async_task=set_groupers.validate()
            .set_task_instance_id("groupers")
            .handle_errors()
            .with_tracing()
            .set_executor("lithops"),
            partial={} | (params_dict.get("groupers") or {}),
            method="call",
        ),
        "er_client_name": Node(
            async_task=set_er_connection.validate()
            .set_task_instance_id("er_client_name")
            .handle_errors()
            .with_tracing()
            .set_executor("lithops"),
            partial=(params_dict.get("er_client_name") or {}),
            method="call",
        ),
        "get_events_data": Node(
            async_task=get_events.validate()
            .set_task_instance_id("get_events_data")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "client": DependsOn("er_client_name"),
                "time_range": DependsOn("time_range"),
                "event_columns": [
                    "id",
                    "time",
                    "event_type",
                    "event_category",
                    "reported_by",
                    "serial_number",
                    "geometry",
                    "created_at",
                    "event_details",
                    "patrols",
                ],
                "event_types": [
                    "balloon_landing",
                    "airstrip_operations",
                    "airstrip_maintenance",
                    "airline_complaint",
                ],
                "raise_on_empty": True,
                "include_details": True,
                "include_updates": False,
                "include_related_events": False,
                "include_null_geometry": False,
                "include_display_values": False,
            }
            | (params_dict.get("get_events_data") or {}),
            method="call",
        ),
        "extract_event_date": Node(
            async_task=extract_column_as_type.validate()
            .set_task_instance_id("extract_event_date")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("get_events_data"),
                "column_name": "time",
                "output_type": "date",
                "output_column_name": "date",
            }
            | (params_dict.get("extract_event_date") or {}),
            method="call",
        ),
        "events_temporal": Node(
            async_task=add_temporal_index.validate()
            .set_task_instance_id("events_temporal")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("extract_event_date"),
                "time_col": "date",
                "groupers": DependsOn("groupers"),
                "cast_to_datetime": True,
                "format": "mixed",
            }
            | (params_dict.get("events_temporal") or {}),
            method="call",
        ),
        "filter_balloon_events": Node(
            async_task=filter_df.validate()
            .set_task_instance_id("filter_balloon_events")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "column_name": "event_type",
                "op": "equal",
                "value": "balloon_landing",
                "df": DependsOn("events_temporal"),
                "reset_index": False,
            }
            | (params_dict.get("filter_balloon_events") or {}),
            method="call",
        ),
        "filter_airstrip_operations": Node(
            async_task=filter_df.validate()
            .set_task_instance_id("filter_airstrip_operations")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "column_name": "event_type",
                "op": "equal",
                "value": "airstrip_operations",
                "df": DependsOn("events_temporal"),
                "reset_index": False,
            }
            | (params_dict.get("filter_airstrip_operations") or {}),
            method="call",
        ),
        "filter_airstrip_maintenance": Node(
            async_task=filter_df.validate()
            .set_task_instance_id("filter_airstrip_maintenance")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "column_name": "event_type",
                "op": "equal",
                "value": "airstrip_maintenance",
                "df": DependsOn("events_temporal"),
                "reset_index": False,
            }
            | (params_dict.get("filter_airstrip_maintenance") or {}),
            method="call",
        ),
        "filter_airline_complaints": Node(
            async_task=filter_df.validate()
            .set_task_instance_id("filter_airline_complaints")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "column_name": "event_type",
                "op": "equal",
                "value": "airline_complaint",
                "df": DependsOn("events_temporal"),
                "reset_index": False,
            }
            | (params_dict.get("filter_airline_complaints") or {}),
            method="call",
        ),
        "process_balloon_details": Node(
            async_task=process_events_details.validate()
            .set_task_instance_id("process_balloon_details")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("filter_balloon_events"),
                "client": DependsOn("er_client_name"),
                "map_to_titles": True,
                "ordered": True,
            }
            | (params_dict.get("process_balloon_details") or {}),
            method="call",
        ),
        "normalize_balloon_values": Node(
            async_task=normalize_json_column.validate()
            .set_task_instance_id("normalize_balloon_values")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "column": "event_details",
                "df": DependsOn("process_balloon_details"),
                "skip_if_not_exists": True,
                "sort_columns": True,
            }
            | (params_dict.get("normalize_balloon_values") or {}),
            method="call",
        ),
        "drop_balloon_prefix": Node(
            async_task=drop_column_prefix.validate()
            .set_task_instance_id("drop_balloon_prefix")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("normalize_balloon_values"),
                "prefix": "event_details__",
                "duplicate_strategy": "keep_original",
            }
            | (params_dict.get("drop_balloon_prefix") or {}),
            method="call",
        ),
        "process_airstrip_details": Node(
            async_task=process_events_details.validate()
            .set_task_instance_id("process_airstrip_details")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("filter_airstrip_operations"),
                "client": DependsOn("er_client_name"),
                "map_to_titles": True,
                "ordered": True,
            }
            | (params_dict.get("process_airstrip_details") or {}),
            method="call",
        ),
        "normalize_airstrip_op_values": Node(
            async_task=normalize_json_column.validate()
            .set_task_instance_id("normalize_airstrip_op_values")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "column": "event_details",
                "df": DependsOn("process_airstrip_details"),
                "skip_if_not_exists": True,
                "sort_columns": True,
            }
            | (params_dict.get("normalize_airstrip_op_values") or {}),
            method="call",
        ),
        "drop_airstrip_op_prefix": Node(
            async_task=drop_column_prefix.validate()
            .set_task_instance_id("drop_airstrip_op_prefix")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("normalize_airstrip_op_values"),
                "prefix": "event_details__",
                "duplicate_strategy": "keep_original",
            }
            | (params_dict.get("drop_airstrip_op_prefix") or {}),
            method="call",
        ),
        "process_airstrip_maint_details": Node(
            async_task=process_events_details.validate()
            .set_task_instance_id("process_airstrip_maint_details")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("filter_airstrip_maintenance"),
                "client": DependsOn("er_client_name"),
                "map_to_titles": True,
                "ordered": True,
            }
            | (params_dict.get("process_airstrip_maint_details") or {}),
            method="call",
        ),
        "normalize_airstrip_maint_vals": Node(
            async_task=normalize_json_column.validate()
            .set_task_instance_id("normalize_airstrip_maint_vals")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "column": "event_details",
                "df": DependsOn("process_airstrip_maint_details"),
                "skip_if_not_exists": True,
                "sort_columns": True,
            }
            | (params_dict.get("normalize_airstrip_maint_vals") or {}),
            method="call",
        ),
        "drop_airstrip_maintenance_prefix": Node(
            async_task=drop_column_prefix.validate()
            .set_task_instance_id("drop_airstrip_maintenance_prefix")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("normalize_airstrip_maint_vals"),
                "prefix": "event_details__",
                "duplicate_strategy": "keep_original",
            }
            | (params_dict.get("drop_airstrip_maintenance_prefix") or {}),
            method="call",
        ),
        "process_airline_comp_details": Node(
            async_task=process_events_details.validate()
            .set_task_instance_id("process_airline_comp_details")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("filter_airline_complaints"),
                "client": DependsOn("er_client_name"),
                "map_to_titles": True,
                "ordered": True,
            }
            | (params_dict.get("process_airline_comp_details") or {}),
            method="call",
        ),
        "normalize_airline_comp_vals": Node(
            async_task=normalize_json_column.validate()
            .set_task_instance_id("normalize_airline_comp_vals")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "column": "event_details",
                "df": DependsOn("process_airline_comp_details"),
                "skip_if_not_exists": True,
                "sort_columns": True,
            }
            | (params_dict.get("normalize_airline_comp_vals") or {}),
            method="call",
        ),
        "drop_airline_complaint_prefix": Node(
            async_task=drop_column_prefix.validate()
            .set_task_instance_id("drop_airline_complaint_prefix")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("normalize_airline_comp_vals"),
                "prefix": "event_details__",
                "duplicate_strategy": "keep_original",
            }
            | (params_dict.get("drop_airline_complaint_prefix") or {}),
            method="call",
        ),
        "map_balloon_columns": Node(
            async_task=map_columns.validate()
            .set_task_instance_id("map_balloon_columns")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("drop_balloon_prefix"),
                "retain_columns": [
                    "date",
                    "Balloon Company",
                    "Where are clients staying?",
                    "# of passengers",
                ],
                "rename_columns": {
                    "Balloon Company": "balloon_company",
                    "Where are clients staying?": "where_are_clients_staying",
                    "# of passengers": "no_of_passengers",
                },
                "raise_if_not_found": False,
            }
            | (params_dict.get("map_balloon_columns") or {}),
            method="call",
        ),
        "remove_balloon_brackets": Node(
            async_task=remove_brackets_from_column.validate()
            .set_task_instance_id("remove_balloon_brackets")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("map_balloon_columns"),
                "columns": [
                    "balloon_company",
                    "where_are_clients_staying",
                ],
            }
            | (params_dict.get("remove_balloon_brackets") or {}),
            method="call",
        ),
        "persist_balloon_landing": Node(
            async_task=persist_df.validate()
            .set_task_instance_id("persist_balloon_landing")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "filetype": "csv",
                "df": DependsOn("remove_balloon_brackets"),
                "filename": "balloon_landing_summary_table",
            }
            | (params_dict.get("persist_balloon_landing") or {}),
            method="call",
        ),
        "map_airstrip_op_columns": Node(
            async_task=map_columns.validate()
            .set_task_instance_id("map_airstrip_op_columns")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("drop_airstrip_op_prefix"),
                "rename_columns": {
                    "Airline": "airline",
                    "Arrival or departure": "arrival_departure",
                    "Attendant": "attendant",
                    "Camp/Lodge": "camp_lodge",
                    "Number of clients": "no_of_clients",
                },
                "raise_if_not_found": False,
            }
            | (params_dict.get("map_airstrip_op_columns") or {}),
            method="call",
        ),
        "remove_airstrip_op_brackets": Node(
            async_task=remove_brackets_from_column.validate()
            .set_task_instance_id("remove_airstrip_op_brackets")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("map_airstrip_op_columns"),
                "columns": [
                    "airline",
                    "arrival_departure",
                    "attendant",
                    "camp_lodge",
                ],
            }
            | (params_dict.get("remove_airstrip_op_brackets") or {}),
            method="call",
        ),
        "replace_airstrip_op_nulls": Node(
            async_task=replace_missing_with_label.validate()
            .set_task_instance_id("replace_airstrip_op_nulls")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("remove_airstrip_op_brackets"),
                "columns": [
                    "camp_lodge",
                ],
                "label": "other",
            }
            | (params_dict.get("replace_airstrip_op_nulls") or {}),
            method="call",
        ),
        "convert_airstrip_op_ints": Node(
            async_task=convert_to_int.validate()
            .set_task_instance_id("convert_airstrip_op_ints")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("replace_airstrip_op_nulls"),
                "columns": [
                    "no_of_clients",
                ],
                "errors": "coerce",
                "fill_value": 0,
                "inplace": False,
            }
            | (params_dict.get("convert_airstrip_op_ints") or {}),
            method="call",
        ),
        "capitalize_camp_lodge": Node(
            async_task=capitalize_text.validate()
            .set_task_instance_id("capitalize_camp_lodge")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("convert_airstrip_op_ints"),
                "column": "camp_lodge",
            }
            | (params_dict.get("capitalize_camp_lodge") or {}),
            method="call",
        ),
        "airstrip_op_summary_table": Node(
            async_task=summarize_df.validate()
            .set_task_instance_id("airstrip_op_summary_table")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("capitalize_camp_lodge"),
                "groupby_cols": [
                    "camp_lodge",
                    "arrival_departure",
                ],
                "summary_params": [
                    {
                        "display_name": "no_of_clients",
                        "aggregator": "sum",
                        "column": "no_of_clients",
                        "decimal_places": 0,
                    },
                ],
                "reset_index": True,
            }
            | (params_dict.get("airstrip_op_summary_table") or {}),
            method="call",
        ),
        "pivot_airstrip_ops": Node(
            async_task=pivot_df.validate()
            .set_task_instance_id("pivot_airstrip_ops")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("airstrip_op_summary_table"),
                "index_col": "camp_lodge",
                "columns_col": "arrival_departure",
                "values_col": "no_of_clients",
                "reset_idx": True,
            }
            | (params_dict.get("pivot_airstrip_ops") or {}),
            method="call",
        ),
        "convert_pivot_int": Node(
            async_task=convert_to_int.validate()
            .set_task_instance_id("convert_pivot_int")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("pivot_airstrip_ops"),
                "columns": [
                    "arrival",
                    "departure",
                ],
                "errors": "coerce",
                "fill_value": 0,
                "inplace": False,
            }
            | (params_dict.get("convert_pivot_int") or {}),
            method="call",
        ),
        "persist_airstrip_operations": Node(
            async_task=persist_df.validate()
            .set_task_instance_id("persist_airstrip_operations")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "filetype": "csv",
                "df": DependsOn("convert_pivot_int"),
                "filename": "airstrip_operations_summary_table",
            }
            | (params_dict.get("persist_airstrip_operations") or {}),
            method="call",
        ),
        "map_airstrip_maintenance": Node(
            async_task=map_columns.validate()
            .set_task_instance_id("map_airstrip_maintenance")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("drop_airstrip_maintenance_prefix"),
                "retain_columns": [
                    "date",
                    "Maintenance type",
                ],
                "rename_columns": {
                    "Maintenance type": "maintenance_type",
                },
                "raise_if_not_found": False,
            }
            | (params_dict.get("map_airstrip_maintenance") or {}),
            method="call",
        ),
        "persist_airstrip_maintenance": Node(
            async_task=persist_df.validate()
            .set_task_instance_id("persist_airstrip_maintenance")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "filetype": "csv",
                "df": DependsOn("map_airstrip_maintenance"),
                "filename": "airstrip_maintenance_summary_table",
            }
            | (params_dict.get("persist_airstrip_maintenance") or {}),
            method="call",
        ),
        "mnc_events_dashboard": Node(
            async_task=gather_dashboard.validate()
            .set_task_instance_id("mnc_events_dashboard")
            .handle_errors()
            .with_tracing()
            .set_executor("lithops"),
            partial={
                "details": DependsOn("workflow_details"),
                "time_range": DependsOn("time_range"),
                "groupers": DependsOn("groupers"),
            }
            | (params_dict.get("mnc_events_dashboard") or {}),
            method="call",
        ),
    }
    graph = Graph(dependencies=dependencies, nodes=nodes)
    results = graph.execute()
    return results
